#!/usr/bin/env python3
"""Fast source and generated-metadata integrity checks."""

from __future__ import annotations

import re
import sys
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]

EMPTY_RUST_ALLOWLIST: dict[str, str] = {
    "crates/php_bench/src/lib.rs": (
        "bench-only marker crate; benchmark implementations live under benches/"
    ),
}

REQUIRED_FILES = [
    "crates/php_vm/src/lib.rs",
    "crates/php_vm/src/vm/mod.rs",
    "crates/php_vm/src/vm/arguments.rs",
    "crates/php_vm/src/vm/dense_method_dispatch.rs",
    "crates/php_vm/src/vm/generator_fiber.rs",
    "crates/php_vm/src/vm/options.rs",
    "crates/php_vm/src/vm/prelude.rs",
    "crates/php_vm/src/vm/result.rs",
    "crates/php_std/src/lib.rs",
    "crates/php_std/src/arginfo.rs",
    "crates/php_std/src/generated/mod.rs",
    "crates/php_std/src/generated/arginfo.rs",
    "scripts/stdlib/generate_arginfo.py",
    "scripts/stdlib/registry_drift.py",
    "scripts/stdlib/registry_drift_allowlist.jsonl",
    "scripts/verify/api_facade_allowlist.txt",
    "scripts/verify/dependency_boundaries.py",
    "scripts/verify/dependency_boundary_allowlist.json",
    "scripts/verify/panic_unwrap_policy.py",
    "scripts/verify/panic_unwrap_allowlist.jsonl",
    "docs/repository-truth-ratchet.md",
    "docs/runtime-module-boundaries.md",
    "docs/performance-mode-matrix.md",
    "docs/panic-unwrap-policy.md",
]

API_FACADE_ROOT_RE = re.compile(
    r"\bphp_(?:vm|runtime)::(?!(?:api|debug|experimental)\b)(?:\{|[A-Za-z_])"
)

VM_MOD_REQUIRED_SNIPPETS = [
    "mod arguments;",
    "mod dense_method_dispatch;",
    "mod generator_fiber;",
    "mod options;",
    "mod prelude;",
    "mod result;",
    "BytecodeLayoutMode, ExecutionFormat, JitBlacklistMode, JitMode, SuperinstructionMode, VmOptions,",
    "pub use result::{VmControlFlow, VmResult};",
    "pub struct Vm",
    "impl Vm",
    "pub fn execute(&self, unit: impl Into<CompiledUnit>) -> VmResult",
]

VM_RESULT_REQUIRED_SNIPPETS = [
    "impl VmResult",
    "pub(crate) fn success(",
    "pub(crate) fn success_with_diagnostics(",
    "pub(super) fn script_exit(",
    "pub(crate) fn runtime_error_with_diagnostic(",
    "pub(super) fn compile_error(",
    "pub(super) fn unsupported(",
    "pub(super) fn propagating_exception(",
]

VM_SUBMODULE_REQUIRED_SNIPPETS = {
    "crates/php_vm/src/vm/arguments.rs": ["use super::prelude::*;"],
    "crates/php_vm/src/vm/dense_method_dispatch.rs": ["use super::prelude::*;"],
    "crates/php_vm/src/vm/generator_fiber.rs": ["use super::prelude::*;"],
    "crates/php_vm/src/vm/prelude.rs": ["pub(super) use super::*;"],
}

VM_SUBMODULE_FORBIDDEN_SNIPPETS = {
    "crates/php_vm/src/vm/arguments.rs": ["use super::*;"],
    "crates/php_vm/src/vm/dense_method_dispatch.rs": ["use super::*;"],
    "crates/php_vm/src/vm/generator_fiber.rs": ["use super::*;"],
}

VM_LIB_REQUIRED_SNIPPETS = [
    "pub mod vm;",
    "pub use vm::{",
    "BytecodeLayoutMode, ExecutionFormat, JitBlacklistMode, JitMode, SuperinstructionMode, Vm,",
]

ARGINFO_REQUIRED_SNIPPETS = [
    "// @generated by scripts/stdlib/generate_arginfo.py",
    "pub struct GeneratedFunctionMetadata",
    "pub struct GeneratedClassMetadata",
    "pub struct GeneratedMethodMetadata",
    "pub struct GeneratedConstantMetadata",
    "pub const GENERATED_FUNCTIONS: &[GeneratedFunctionMetadata] = &[",
    "pub const GENERATED_CLASSES: &[GeneratedClassMetadata] = &[",
    "pub const GENERATED_METHODS: &[GeneratedMethodMetadata] = &[",
    "pub const GENERATED_CONSTANTS: &[GeneratedConstantMetadata] = &[",
    "pub fn function_metadata(name: &str) -> Option<&'static GeneratedFunctionMetadata>",
    "pub fn class_metadata(name: &str) -> Option<&'static GeneratedClassMetadata>",
    "pub fn method_metadata(",
    "pub fn constant_metadata(",
    'name: "strlen"',
    'name: "range"',
    'name: "var_dump"',
    'name: "Closure"',
    'name: "DateTime"',
    'name: "PHP_VERSION"',
]

GENERATED_COUNT_CONSTANTS = [
    "GENERATED_ARGINFO_FUNCTION_COUNT",
    "GENERATED_ARGINFO_CLASS_COUNT",
    "GENERATED_ARGINFO_METHOD_COUNT",
    "GENERATED_ARGINFO_CONSTANT_COUNT",
]

PHP_STD_CONSUMED_SYMBOLS = [
    "generated::arginfo::function_metadata",
    "generated::arginfo::constant_metadata",
    "generated::arginfo::class_metadata",
    "generated::arginfo::GENERATED_CLASSES",
]

RUNTIME_MODULE_BOUNDARY_DOC = "docs/runtime-module-boundaries.md"

DOC_STALE_IMPORTS = {
    "docs/runtime-semantics-status.md": [
        "php_vm::Vm",
        "php_runtime::Value",
    ],
}


@dataclass(frozen=True)
class ApiFacadeAllowlistEntry:
    kind: str
    pattern: str
    reason: str


class IntegrityError(Exception):
    """One or more integrity checks failed."""


def rel(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def read_required(relative: str) -> str:
    path = ROOT / relative
    if not path.is_file():
        raise IntegrityError(f"missing required file: {relative}")
    text = path.read_text(encoding="utf-8")
    if not text.strip():
        raise IntegrityError(f"required file is empty: {relative}")
    return text


def meaningful_rust_text(text: str) -> bool:
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        if stripped.startswith("//") or stripped in {"{", "}"}:
            continue
        return True
    return False


def check_required_files() -> None:
    for relative in REQUIRED_FILES:
        read_required(relative)


def check_empty_rust_modules() -> None:
    for path in sorted((ROOT / "crates").glob("*/src/**/*.rs")):
        relative = rel(path)
        text = path.read_text(encoding="utf-8")
        if meaningful_rust_text(text):
            continue
        if relative in EMPTY_RUST_ALLOWLIST:
            continue
        raise IntegrityError(
            f"empty Rust source without allowlist reason: {relative}. "
            "Add real module contents or document the reason in "
            "EMPTY_RUST_ALLOWLIST."
        )


def require_snippets(label: str, text: str, snippets: list[str]) -> None:
    missing = [snippet for snippet in snippets if snippet not in text]
    if missing:
        joined = "\n  - ".join(missing)
        raise IntegrityError(f"{label} is missing required text:\n  - {joined}")


def forbid_snippets(label: str, text: str, snippets: list[str]) -> None:
    present = [snippet for snippet in snippets if snippet in text]
    if present:
        joined = "\n  - ".join(present)
        raise IntegrityError(f"{label} contains forbidden text:\n  - {joined}")


def check_vm_module_wiring() -> None:
    vm_mod = read_required("crates/php_vm/src/vm/mod.rs")
    vm_lib = read_required("crates/php_vm/src/lib.rs")
    vm_result = read_required("crates/php_vm/src/vm/result.rs")
    require_snippets("php_vm::vm module", vm_mod, VM_MOD_REQUIRED_SNIPPETS)
    require_snippets("php_vm crate facade", vm_lib, VM_LIB_REQUIRED_SNIPPETS)
    require_snippets("php_vm::vm result module", vm_result, VM_RESULT_REQUIRED_SNIPPETS)
    for relative, snippets in VM_SUBMODULE_REQUIRED_SNIPPETS.items():
        require_snippets(relative, read_required(relative), snippets)
    for relative, snippets in VM_SUBMODULE_FORBIDDEN_SNIPPETS.items():
        forbid_snippets(relative, read_required(relative), snippets)

    declared_modules = set(re.findall(r"^mod\s+([A-Za-z0-9_]+);", vm_mod, re.MULTILINE))
    sibling_modules = {
        path.stem
        for path in (ROOT / "crates/php_vm/src/vm").glob("*.rs")
        if path.name != "mod.rs"
    }
    if declared_modules != sibling_modules:
        missing = sorted(sibling_modules - declared_modules)
        extra = sorted(declared_modules - sibling_modules)
        details = []
        if missing:
            details.append(f"missing declarations: {', '.join(missing)}")
        if extra:
            details.append(f"declarations without files: {', '.join(extra)}")
        raise IntegrityError(
            "php_vm::vm module declarations do not match sibling files: "
            + "; ".join(details)
        )


def generated_count(text: str, name: str) -> int:
    match = re.search(rf"pub const {name}: usize = (\d+);", text)
    if not match:
        raise IntegrityError(f"generated arginfo is missing count constant: {name}")
    return int(match.group(1))


def check_generated_arginfo() -> None:
    generated_mod = read_required("crates/php_std/src/generated/mod.rs")
    if "pub mod arginfo;" not in generated_mod:
        raise IntegrityError("php_std::generated does not expose generated::arginfo")

    arginfo = read_required("crates/php_std/src/generated/arginfo.rs")
    require_snippets("generated arginfo", arginfo, ARGINFO_REQUIRED_SNIPPETS)
    for constant in GENERATED_COUNT_CONSTANTS:
        count = generated_count(arginfo, constant)
        if count <= 0:
            raise IntegrityError(f"generated arginfo count must be non-zero: {constant}")


def check_php_std_consumers() -> None:
    combined = "\n".join(
        [
            read_required("crates/php_std/src/lib.rs"),
            read_required("crates/php_std/src/arginfo.rs"),
        ]
    )
    require_snippets("php_std generated-arginfo consumers", combined, PHP_STD_CONSUMED_SYMBOLS)


def read_api_facade_allowlist() -> list[ApiFacadeAllowlistEntry]:
    entries: list[ApiFacadeAllowlistEntry] = []
    text = read_required("scripts/verify/api_facade_allowlist.txt")
    for index, line in enumerate(text.splitlines(), start=1):
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        parts = stripped.split("|", 2)
        if len(parts) != 3:
            raise IntegrityError(
                "api facade allowlist entries must use "
                f"`kind|pattern|reason`: line {index}"
            )
        kind, pattern, reason = (part.strip() for part in parts)
        if kind not in {"path", "path-prefix"}:
            raise IntegrityError(
                f"api facade allowlist line {index} has unsupported kind: {kind}"
            )
        if not pattern or not reason:
            raise IntegrityError(
                f"api facade allowlist line {index} needs a pattern and reason"
            )
        entries.append(ApiFacadeAllowlistEntry(kind, pattern, reason))
    return entries


def api_facade_root_import_allowed(
    relative: str, entries: list[ApiFacadeAllowlistEntry]
) -> bool:
    for entry in entries:
        if entry.kind == "path" and relative == entry.pattern:
            return True
        if entry.kind == "path-prefix" and relative.startswith(entry.pattern):
            return True
    return False


def check_api_facade_imports() -> None:
    entries = read_api_facade_allowlist()
    violations: list[str] = []
    for path in sorted((ROOT / "crates").glob("*/src/**/*.rs")):
        relative = rel(path)
        if api_facade_root_import_allowed(relative, entries):
            continue
        for line_number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
            stripped = line.strip()
            if stripped.startswith("//"):
                continue
            if API_FACADE_ROOT_RE.search(line):
                violations.append(f"{relative}:{line_number}: {stripped}")
    if violations:
        joined = "\n  - ".join(violations[:50])
        extra = "" if len(violations) <= 50 else f"\n  ... {len(violations) - 50} more"
        raise IntegrityError(
            "root php_vm/php_runtime imports must use api/debug/experimental facades "
            "or be documented in scripts/verify/api_facade_allowlist.txt:\n"
            f"  - {joined}{extra}"
        )


def check_runtime_module_boundaries_doc() -> None:
    lib = read_required("crates/php_runtime/src/lib.rs")
    doc = read_required(RUNTIME_MODULE_BOUNDARY_DOC)
    modules = sorted(re.findall(r"^pub mod\s+([A-Za-z0-9_]+);", lib, re.MULTILINE))
    missing = [module for module in modules if f"`{module}`" not in doc]
    if missing:
        raise IntegrityError(
            f"{RUNTIME_MODULE_BOUNDARY_DOC} does not categorize runtime modules: "
            + ", ".join(missing)
        )


def check_doc_import_guidance() -> None:
    for relative, stale_imports in DOC_STALE_IMPORTS.items():
        text = read_required(relative)
        present = [stale for stale in stale_imports if stale in text]
        if present:
            raise IntegrityError(
                f"{relative} contains stale root facade guidance: "
                + ", ".join(present)
            )


def main() -> int:
    checks = [
        check_required_files,
        check_empty_rust_modules,
        check_vm_module_wiring,
        check_generated_arginfo,
        check_php_std_consumers,
        check_api_facade_imports,
        check_runtime_module_boundaries_doc,
        check_doc_import_guidance,
    ]
    try:
        for check in checks:
            check()
    except IntegrityError as error:
        print(f"[fail] source integrity: {error}", file=sys.stderr)
        return 1
    print("[ok] source integrity checks passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
