#!/usr/bin/env python3
"""Fast source and generated-metadata integrity checks."""

from __future__ import annotations

import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]

EMPTY_RUST_ALLOWLIST: dict[str, str] = {
    "crates/php_bench/src/lib.rs": (
        "bench-only marker crate; benchmark implementations live under benches/"
    ),
}

REQUIRED_FILES = [
    "crates/php_vm/src/lib.rs",
    "crates/php_vm/src/vm/mod.rs",
    "crates/php_vm/src/vm/arguments.rs",
    "crates/php_vm/src/vm/options.rs",
    "crates/php_vm/src/vm/result.rs",
    "crates/php_std/src/lib.rs",
    "crates/php_std/src/arginfo.rs",
    "crates/php_std/src/generated/mod.rs",
    "crates/php_std/src/generated/arginfo.rs",
    "scripts/stdlib/generate_arginfo.py",
]

VM_MOD_REQUIRED_SNIPPETS = [
    "mod arguments;",
    "mod options;",
    "mod result;",
    "pub use options::{ExecutionFormat, JitBlacklistMode, JitMode, SuperinstructionMode, VmOptions};",
    "pub use result::{VmControlFlow, VmResult};",
    "pub struct Vm",
    "impl Vm",
    "pub fn execute(&self, unit: impl Into<CompiledUnit>) -> VmResult",
]

VM_LIB_REQUIRED_SNIPPETS = [
    "pub mod vm;",
    "pub use vm::{",
    "Vm, VmOptions, VmResult",
]

ARGINFO_REQUIRED_SNIPPETS = [
    "// @generated by scripts/stdlib/generate_arginfo.py",
    "pub struct GeneratedFunctionMetadata",
    "pub struct GeneratedClassMetadata",
    "pub struct GeneratedMethodMetadata",
    "pub struct GeneratedConstantMetadata",
    "pub const GENERATED_FUNCTIONS: &[GeneratedFunctionMetadata] = &[",
    "pub const GENERATED_CLASSES: &[GeneratedClassMetadata] = &[",
    "pub const GENERATED_METHODS: &[GeneratedMethodMetadata] = &[",
    "pub const GENERATED_CONSTANTS: &[GeneratedConstantMetadata] = &[",
    "pub fn function_metadata(name: &str) -> Option<&'static GeneratedFunctionMetadata>",
    "pub fn class_metadata(name: &str) -> Option<&'static GeneratedClassMetadata>",
    "pub fn method_metadata(",
    "pub fn constant_metadata(",
    'name: "strlen"',
    'name: "range"',
    'name: "var_dump"',
    'name: "Closure"',
    'name: "DateTime"',
    'name: "PHP_VERSION"',
]

GENERATED_COUNT_CONSTANTS = [
    "GENERATED_ARGINFO_FUNCTION_COUNT",
    "GENERATED_ARGINFO_CLASS_COUNT",
    "GENERATED_ARGINFO_METHOD_COUNT",
    "GENERATED_ARGINFO_CONSTANT_COUNT",
]

PHP_STD_CONSUMED_SYMBOLS = [
    "generated::arginfo::function_metadata",
    "generated::arginfo::constant_metadata",
    "generated::arginfo::class_metadata",
    "generated::arginfo::GENERATED_CLASSES",
]


class IntegrityError(Exception):
    """One or more integrity checks failed."""


def rel(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def read_required(relative: str) -> str:
    path = ROOT / relative
    if not path.is_file():
        raise IntegrityError(f"missing required file: {relative}")
    text = path.read_text(encoding="utf-8")
    if not text.strip():
        raise IntegrityError(f"required file is empty: {relative}")
    return text


def meaningful_rust_text(text: str) -> bool:
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        if stripped.startswith("//") or stripped in {"{", "}"}:
            continue
        return True
    return False


def check_required_files() -> None:
    for relative in REQUIRED_FILES:
        read_required(relative)


def check_empty_rust_modules() -> None:
    for path in sorted((ROOT / "crates").glob("*/src/**/*.rs")):
        relative = rel(path)
        text = path.read_text(encoding="utf-8")
        if meaningful_rust_text(text):
            continue
        if relative in EMPTY_RUST_ALLOWLIST:
            continue
        raise IntegrityError(
            f"empty Rust source without allowlist reason: {relative}. "
            "Add real module contents or document the reason in "
            "EMPTY_RUST_ALLOWLIST."
        )


def require_snippets(label: str, text: str, snippets: list[str]) -> None:
    missing = [snippet for snippet in snippets if snippet not in text]
    if missing:
        joined = "\n  - ".join(missing)
        raise IntegrityError(f"{label} is missing required text:\n  - {joined}")


def check_vm_module_wiring() -> None:
    vm_mod = read_required("crates/php_vm/src/vm/mod.rs")
    vm_lib = read_required("crates/php_vm/src/lib.rs")
    require_snippets("php_vm::vm module", vm_mod, VM_MOD_REQUIRED_SNIPPETS)
    require_snippets("php_vm crate facade", vm_lib, VM_LIB_REQUIRED_SNIPPETS)


def generated_count(text: str, name: str) -> int:
    match = re.search(rf"pub const {name}: usize = (\d+);", text)
    if not match:
        raise IntegrityError(f"generated arginfo is missing count constant: {name}")
    return int(match.group(1))


def check_generated_arginfo() -> None:
    generated_mod = read_required("crates/php_std/src/generated/mod.rs")
    if "pub mod arginfo;" not in generated_mod:
        raise IntegrityError("php_std::generated does not expose generated::arginfo")

    arginfo = read_required("crates/php_std/src/generated/arginfo.rs")
    require_snippets("generated arginfo", arginfo, ARGINFO_REQUIRED_SNIPPETS)
    for constant in GENERATED_COUNT_CONSTANTS:
        count = generated_count(arginfo, constant)
        if count <= 0:
            raise IntegrityError(f"generated arginfo count must be non-zero: {constant}")


def check_php_std_consumers() -> None:
    combined = "\n".join(
        [
            read_required("crates/php_std/src/lib.rs"),
            read_required("crates/php_std/src/arginfo.rs"),
        ]
    )
    require_snippets("php_std generated-arginfo consumers", combined, PHP_STD_CONSUMED_SYMBOLS)


def main() -> int:
    checks = [
        check_required_files,
        check_empty_rust_modules,
        check_vm_module_wiring,
        check_generated_arginfo,
        check_php_std_consumers,
    ]
    try:
        for check in checks:
            check()
    except IntegrityError as error:
        print(f"[fail] source integrity: {error}", file=sys.stderr)
        return 1
    print("[ok] source integrity checks passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
