// @generated by scripts/stdlib/generate_extension_surfaces.py
// canonical external extension lifecycle metadata; edit fixtures/stdlib/extensions instead.

use php_runtime::api::ExtensionCapability;

#[derive(Clone, Copy, Debug)]
pub struct GeneratedExtensionMetadata {
    pub name: &'static str,
    pub version: &'static str,
    pub dependencies: &'static [&'static str],
    pub capabilities: &'static [ExtensionCapability],
    pub state_slot: Option<&'static str>,
}

pub const APCU: GeneratedExtensionMetadata = GeneratedExtensionMetadata {
    name: "apcu",
    version: "5.1",
    dependencies: &[],
    capabilities: &[
        ExtensionCapability::Clock,
        ExtensionCapability::ProcessSharedState,
    ],
    state_slot: Some("ApcuState"),
};

pub const CTYPE: GeneratedExtensionMetadata = GeneratedExtensionMetadata {
    name: "ctype",
    version: "8.5.7",
    dependencies: &[],
    capabilities: &[],
    state_slot: None,
};
