//! Arrays builtin registry slice.

use super::core;
use crate::builtins::{BuiltinCompatibility, BuiltinEntry};

pub(in crate::builtins) const ENTRIES: &[BuiltinEntry] = &[
    BuiltinEntry::new(
        "array_all",
        core::builtin_array_callback_requires_vm,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "array_any",
        core::builtin_array_callback_requires_vm,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "array_chunk",
        core::builtin_array_chunk,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "array_column",
        core::builtin_array_column,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "array_filter",
        core::builtin_array_callback_requires_vm,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "array_fill",
        core::builtin_array_fill,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "array_find",
        core::builtin_array_callback_requires_vm,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "array_find_key",
        core::builtin_array_callback_requires_vm,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "array_flip",
        core::builtin_array_flip,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "array_is_list",
        core::builtin_array_is_list,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "array_key_exists",
        core::builtin_array_key_exists,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "array_key_first",
        core::builtin_array_key_first,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "array_key_last",
        core::builtin_array_key_last,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "array_keys",
        core::builtin_array_keys,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "array_map",
        core::builtin_array_callback_requires_vm,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "array_merge",
        core::builtin_array_merge,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "array_merge_recursive",
        core::builtin_array_merge_recursive,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "array_pad",
        core::builtin_array_pad,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "array_pop",
        core::builtin_array_pop,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "array_push",
        core::builtin_array_push,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "array_rand",
        core::builtin_array_rand,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "array_reduce",
        core::builtin_array_callback_requires_vm,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "array_replace",
        core::builtin_array_replace,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "array_replace_recursive",
        core::builtin_array_replace_recursive,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "array_reverse",
        core::builtin_array_reverse,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "array_search",
        core::builtin_array_search,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "array_shift",
        core::builtin_array_shift,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "array_slice",
        core::builtin_array_slice,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "array_splice",
        core::builtin_array_splice,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "array_unshift",
        core::builtin_array_unshift,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "array_values",
        core::builtin_array_values,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "array_walk",
        core::builtin_array_callback_requires_vm,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "arsort",
        core::builtin_array_sort_requires_vm,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "asort",
        core::builtin_array_sort_requires_vm,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new("count", core::builtin_count, BuiltinCompatibility::Php),
    BuiltinEntry::new(
        "in_array",
        core::builtin_in_array,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "krsort",
        core::builtin_array_sort_requires_vm,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "ksort",
        core::builtin_array_sort_requires_vm,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "natcasesort",
        core::builtin_array_sort_requires_vm,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "natsort",
        core::builtin_array_sort_requires_vm,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new("range", core::builtin_range, BuiltinCompatibility::Php),
    BuiltinEntry::new(
        "rsort",
        core::builtin_array_sort_requires_vm,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "sort",
        core::builtin_array_sort_requires_vm,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "uasort",
        core::builtin_array_sort_requires_vm,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "uksort",
        core::builtin_array_sort_requires_vm,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "usort",
        core::builtin_array_sort_requires_vm,
        BuiltinCompatibility::Php,
    ),
];
