//! Reflection builtin registry slice.

use crate::Value;
use crate::builtins::{
    BuiltinCompatibility, BuiltinContext, BuiltinEntry, BuiltinError, BuiltinResult,
    RuntimeSourceSpan,
};

pub(in crate::builtins) const ENTRIES: &[BuiltinEntry] = &[
    BuiltinEntry::new(
        "call_user_func",
        builtin_symbol_introspection_requires_vm,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "call_user_func_array",
        builtin_symbol_introspection_requires_vm,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "class_exists",
        builtin_symbol_introspection_requires_vm,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "constant",
        builtin_symbol_introspection_requires_vm,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "defined",
        builtin_symbol_introspection_requires_vm,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "enum_exists",
        builtin_symbol_introspection_requires_vm,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "extension_loaded",
        builtin_symbol_introspection_requires_vm,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "forward_static_call",
        builtin_symbol_introspection_requires_vm,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "func_get_arg",
        builtin_symbol_introspection_requires_vm,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "debug_backtrace",
        builtin_symbol_introspection_requires_vm,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "debug_print_backtrace",
        builtin_symbol_introspection_requires_vm,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "func_get_args",
        builtin_symbol_introspection_requires_vm,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "func_num_args",
        builtin_symbol_introspection_requires_vm,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "function_exists",
        builtin_symbol_introspection_requires_vm,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "get_called_class",
        builtin_symbol_introspection_requires_vm,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "get_class",
        builtin_symbol_introspection_requires_vm,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "get_class_methods",
        builtin_symbol_introspection_requires_vm,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "get_class_vars",
        builtin_symbol_introspection_requires_vm,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "get_declared_classes",
        builtin_symbol_introspection_requires_vm,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "get_declared_interfaces",
        builtin_symbol_introspection_requires_vm,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "get_declared_traits",
        builtin_symbol_introspection_requires_vm,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "get_loaded_extensions",
        builtin_symbol_introspection_requires_vm,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "get_mangled_object_vars",
        builtin_symbol_introspection_requires_vm,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "get_object_vars",
        builtin_symbol_introspection_requires_vm,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "get_parent_class",
        builtin_symbol_introspection_requires_vm,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "interface_exists",
        builtin_symbol_introspection_requires_vm,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "is_a",
        builtin_symbol_introspection_requires_vm,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "is_subclass_of",
        builtin_symbol_introspection_requires_vm,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "method_exists",
        builtin_symbol_introspection_requires_vm,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "property_exists",
        builtin_symbol_introspection_requires_vm,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "trait_exists",
        builtin_symbol_introspection_requires_vm,
        BuiltinCompatibility::Php,
    ),
];

pub(in crate::builtins::modules) fn builtin_symbol_introspection_requires_vm(
    _context: &mut BuiltinContext<'_>,
    _args: Vec<Value>,
    _span: RuntimeSourceSpan,
) -> BuiltinResult {
    Err(BuiltinError::new(
        "E_PHP_RUNTIME_SYMBOL_CONTEXT_REQUIRED",
        "symbol introspection builtins require VM symbol tables and autoload state",
    ))
}
