<?php
require "lib/page.php";

demo_title("phrust PHP webserver demo");

$examples = [
    ["Calculator from GET parameters", "/calculate.php?a=8&b=5"],
    ["Loop and array rendering", "/counter.php?n=6"],
    ["POST form handling", "/hello.php"],
    ["Response headers and status", "/response.php"],
];

echo "<p>This page is generated by PHP running inside phrust-server.</p>\n";

echo "<h2>Examples</h2>\n";
echo "<ul>\n";
foreach ($examples as $example) {
    echo "<li><a href=\"", demo_value($example[1]), "\">", demo_value($example[0]), "</a></li>\n";
}
echo "</ul>\n";

echo "<h2>Current request</h2>\n";
echo "<dl>\n";
echo "<dt>Method</dt><dd>", demo_value($_SERVER["REQUEST_METHOD"]), "</dd>\n";
echo "<dt>URI</dt><dd>", demo_value($_SERVER["REQUEST_URI"]), "</dd>\n";
echo "<dt>Script</dt><dd>", demo_value($_SERVER["SCRIPT_NAME"]), "</dd>\n";
echo "</dl>\n";

demo_footer();
