pub(super) struct ModulePlanSpec {
    pub(super) name: &'static str,
    pub(super) scope: &'static [&'static str],
    pub(super) non_scope: &'static [&'static str],
    pub(super) source_places: &'static [&'static str],
    pub(super) target_gates: &'static [&'static str],
    pub(super) next_step: &'static str,
    pub(super) leverage: usize,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(super) struct ExtensionPolicySpec {
    pub(super) extension: &'static str,
    pub(super) policy: &'static str,
    pub(super) required_for_core: bool,
    pub(super) required_for_composer: bool,
    pub(super) required_for_framework: bool,
    pub(super) needs_stub: bool,
    pub(super) needs_implementation: bool,
    pub(super) implementation_class: &'static str,
    pub(super) fixture_or_phpt_example: &'static str,
    pub(super) planned_solution_layer: &'static str,
    pub(super) next_action: &'static str,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(super) struct KnownGapSpec {
    pub(super) id: &'static str,
    pub(super) title: &'static str,
    pub(super) reference_behavior: &'static str,
    pub(super) current_rust_behavior: &'static str,
    pub(super) fixture_or_phpt_example: &'static str,
    pub(super) planned_solution_layer: &'static str,
}

pub(super) const EXTENSION_POLICY: &[ExtensionPolicySpec] = &[
    ExtensionPolicySpec {
        extension: "dom",
        policy: "optional",
        required_for_core: false,
        required_for_composer: false,
        required_for_framework: true,
        needs_stub: true,
        needs_implementation: false,
        implementation_class: "stub-only",
        fixture_or_phpt_example: "ext/dom/tests/DOMDocument_loadHTML_basic.phpt",
        planned_solution_layer: "future XML/DOM extension layer",
        next_action: "Keep visible in triage; add stubs only when composer/framework tests require them.",
    },
    ExtensionPolicySpec {
        extension: "xml",
        policy: "optional",
        required_for_core: false,
        required_for_composer: false,
        required_for_framework: true,
        needs_stub: true,
        needs_implementation: false,
        implementation_class: "stub-only",
        fixture_or_phpt_example: "ext/xml/tests/xml_parse_into_struct_variation.phpt",
        planned_solution_layer: "future XML extension layer",
        next_action: "Classify XML parser failures separately from core syntax/runtime failures.",
    },
    ExtensionPolicySpec {
        extension: "simplexml",
        policy: "optional",
        required_for_core: false,
        required_for_composer: false,
        required_for_framework: true,
        needs_stub: true,
        needs_implementation: false,
        implementation_class: "stub-only",
        fixture_or_phpt_example: "ext/simplexml/tests/001.phpt",
        planned_solution_layer: "future XML/SimpleXML extension layer",
        next_action: "Defer implementation until XML support exists; keep PHPTs counted.",
    },
    ExtensionPolicySpec {
        extension: "xsl",
        policy: "optional",
        required_for_core: false,
        required_for_composer: false,
        required_for_framework: false,
        needs_stub: true,
        needs_implementation: false,
        implementation_class: "stub-only",
        fixture_or_phpt_example: "ext/xsl/tests/XSLTProcessor_callables.phpt",
        planned_solution_layer: "future XML/XSL extension layer",
        next_action: "Defer XSLT behavior until DOM/XML support exists; keep PHPTs counted.",
    },
    ExtensionPolicySpec {
        extension: "pdo",
        policy: "optional",
        required_for_core: false,
        required_for_composer: false,
        required_for_framework: true,
        needs_stub: true,
        needs_implementation: false,
        implementation_class: "stub-only",
        fixture_or_phpt_example: "ext/pdo/tests/pdo_001.phpt",
        planned_solution_layer: "future database extension layer",
        next_action: "Keep database API failures out of core runtime gates while preserving counts.",
    },
    ExtensionPolicySpec {
        extension: "pdo_sqlite",
        policy: "required-framework",
        required_for_core: false,
        required_for_composer: false,
        required_for_framework: true,
        needs_stub: false,
        needs_implementation: true,
        implementation_class: "real-implementation-required",
        fixture_or_phpt_example: "ext/pdo_sqlite/tests/bug33841.phpt",
        planned_solution_layer: "future database extension layer",
        next_action: "Keep unavailable until PDO core and real SQLite-backed semantics exist.",
    },
    ExtensionPolicySpec {
        extension: "sqlite3",
        policy: "required-framework",
        required_for_core: false,
        required_for_composer: false,
        required_for_framework: true,
        needs_stub: false,
        needs_implementation: true,
        implementation_class: "real-implementation-required",
        fixture_or_phpt_example: "ext/sqlite3/tests/sqlite3_01_open.phpt",
        planned_solution_layer: "future database extension layer",
        next_action: "Choose an approved SQLite dependency and implement real query semantics before enabling.",
    },
    ExtensionPolicySpec {
        extension: "mysqli",
        policy: "out-of-scope",
        required_for_core: false,
        required_for_composer: false,
        required_for_framework: false,
        needs_stub: false,
        needs_implementation: false,
        implementation_class: "out-of-scope",
        fixture_or_phpt_example: "ext/mysqli/tests/mysqli_connect.phpt",
        planned_solution_layer: "future optional database extension package",
        next_action: "Keep network database support out of scope unless explicitly accepted.",
    },
    ExtensionPolicySpec {
        extension: "mysqlnd",
        policy: "out-of-scope",
        required_for_core: false,
        required_for_composer: false,
        required_for_framework: false,
        needs_stub: false,
        needs_implementation: false,
        implementation_class: "out-of-scope",
        fixture_or_phpt_example: "ext/mysqlnd",
        planned_solution_layer: "extension policy",
        next_action: "No standalone PHPT corpus rows are indexed; keep as out-of-scope driver internals unless MySQL support is requested.",
    },
    ExtensionPolicySpec {
        extension: "soap",
        policy: "out-of-scope",
        required_for_core: false,
        required_for_composer: false,
        required_for_framework: false,
        needs_stub: false,
        needs_implementation: false,
        implementation_class: "out-of-scope",
        fixture_or_phpt_example: "ext/soap/tests/server001.phpt",
        planned_solution_layer: "extension policy",
        next_action: "Keep failures documented as extension-policy non-green unless scope changes.",
    },
    ExtensionPolicySpec {
        extension: "intl",
        policy: "optional",
        required_for_core: false,
        required_for_composer: false,
        required_for_framework: true,
        needs_stub: true,
        needs_implementation: false,
        implementation_class: "stub-only",
        fixture_or_phpt_example: "ext/intl/tests/collator_create.phpt",
        planned_solution_layer: "future intl/ICU extension layer",
        next_action: "Defer ICU parity; add targeted stubs only for framework smoke blockers.",
    },
    ExtensionPolicySpec {
        extension: "mbstring",
        policy: "required-composer",
        required_for_core: false,
        required_for_composer: true,
        required_for_framework: true,
        needs_stub: true,
        needs_implementation: true,
        implementation_class: "real-implementation-required",
        fixture_or_phpt_example: "ext/mbstring/tests/mb_strlen_basic.phpt",
        planned_solution_layer: "php_std/php_runtime string builtins",
        next_action: "Plan a bounded UTF-8 string MVP after standard.strings is stable.",
    },
    ExtensionPolicySpec {
        extension: "gd",
        policy: "out-of-scope",
        required_for_core: false,
        required_for_composer: false,
        required_for_framework: false,
        needs_stub: false,
        needs_implementation: false,
        implementation_class: "out-of-scope",
        fixture_or_phpt_example: "ext/gd/tests/bug39780.phpt",
        planned_solution_layer: "extension policy",
        next_action: "Keep image-processing PHPTs visible but outside core policy-green.",
    },
    ExtensionPolicySpec {
        extension: "phar",
        policy: "required-composer",
        required_for_core: false,
        required_for_composer: true,
        required_for_framework: true,
        needs_stub: true,
        needs_implementation: true,
        implementation_class: "real-implementation-required",
        fixture_or_phpt_example: "ext/phar/tests/phar_oo_001.phpt",
        planned_solution_layer: "php_runtime filesystem/archive layer",
        next_action: "Define a read-only PHAR MVP after filesystem.streams is stable.",
    },
    ExtensionPolicySpec {
        extension: "opcache",
        policy: "out-of-scope",
        required_for_core: false,
        required_for_composer: false,
        required_for_framework: false,
        needs_stub: false,
        needs_implementation: false,
        implementation_class: "out-of-scope",
        fixture_or_phpt_example: "ext/opcache/tests/opcache_enable_noop_001.phpt",
        planned_solution_layer: "extension policy",
        next_action: "Keep Opcache/JIT behavior excluded from runtime correctness scope.",
    },
    ExtensionPolicySpec {
        extension: "session",
        policy: "required-framework",
        required_for_core: false,
        required_for_composer: false,
        required_for_framework: true,
        needs_stub: false,
        needs_implementation: true,
        implementation_class: "real-implementation-required",
        fixture_or_phpt_example: "ext/session/tests/session_basic2.phpt",
        planned_solution_layer: "future request/runtime state layer",
        next_action: "Implement deterministic CLI-only session state only after request-local state and superglobals are ready.",
    },
    ExtensionPolicySpec {
        extension: "sapi",
        policy: "out-of-scope",
        required_for_core: false,
        required_for_composer: false,
        required_for_framework: false,
        needs_stub: false,
        needs_implementation: false,
        implementation_class: "out-of-scope",
        fixture_or_phpt_example: "sapi/phpdbg/tests/print_001.phpt",
        planned_solution_layer: "target CLI/SAPI policy",
        next_action: "Route CLI-compatible tests to phpt.cli and leave CGI/FPM/PHPDBG explicit.",
    },
];

pub(super) const KNOWN_GAP_CATALOG: &[KnownGapSpec] = &[
    KnownGapSpec {
        id: "runtime-error-or-diagnostic",
        title: "Runtime error or diagnostic mismatch",
        reference_behavior: "PHP emits the exact warning, notice, fatal, stack, and exit behavior expected by the PHPT oracle.",
        current_rust_behavior: "The target exits or formats diagnostics differently from PHP for this baseline fingerprint.",
        fixture_or_phpt_example: "Zend/tests/basic/002.phpt",
        planned_solution_layer: "php_runtime/php_vm diagnostics and error channel",
    },
    KnownGapSpec {
        id: "runtime-output-mismatch",
        title: "Runtime output mismatch",
        reference_behavior: "PHP stdout and stderr match the PHPT expectation after normal EXPECT/EXPECTF/EXPECTREGEX handling.",
        current_rust_behavior: "The target completes but emits different observable output.",
        fixture_or_phpt_example: "ext/standard/tests/strings/echo.phpt",
        planned_solution_layer: "php_runtime builtins, php_vm execution semantics, or output buffering",
    },
    KnownGapSpec {
        id: "runtime-unsupported-feature",
        title: "Unsupported runtime feature",
        reference_behavior: "PHP executes the language or builtin feature covered by the PHPT.",
        current_rust_behavior: "The runtime or VM reports an unsupported/not-implemented diagnostic.",
        fixture_or_phpt_example: "Zend/tests/traits/error_001.phpt",
        planned_solution_layer: "php_ir/php_runtime/php_vm feature implementation",
    },
    KnownGapSpec {
        id: "frontend-parse-or-compile",
        title: "Frontend parse or compile gap",
        reference_behavior: "PHP accepts the source or reports the same syntax/compile-time diagnostic as the PHPT expects.",
        current_rust_behavior: "The lexer, parser, semantic frontend, or IR lowering rejects or lowers the source differently.",
        fixture_or_phpt_example: "Zend/tests/parser/heredoc_001.phpt",
        planned_solution_layer: "php_syntax/php_ast/php_semantics/php_ir",
    },
    KnownGapSpec {
        id: "runtime-timeout",
        title: "Runtime timeout",
        reference_behavior: "PHP completes the PHPT within the runner timeout or skips it deterministically.",
        current_rust_behavior: "The target exceeds the PHPT timeout budget.",
        fixture_or_phpt_example: "Zend/tests/loop/while_001.phpt",
        planned_solution_layer: "php_vm control flow, termination, or performance",
    },
    KnownGapSpec {
        id: "phpt-runner-section",
        title: "Unsupported PHPT runner section",
        reference_behavior: "PHP run-tests handles the section and passes the transformed test to the target correctly.",
        current_rust_behavior: "The PHPT runner marks the test BORK because this section is not yet supported.",
        fixture_or_phpt_example: "ext/standard/tests/file/file_variation.phpt",
        planned_solution_layer: "php_phpt_tools runner section handling",
    },
    KnownGapSpec {
        id: "needs-triage",
        title: "Needs focused triage",
        reference_behavior: "PHP behavior is known through the PHPT oracle but the owning failure class is not yet specific enough.",
        current_rust_behavior: "The fingerprint is retained as known non-green until a narrower owner and implementation path is assigned.",
        fixture_or_phpt_example: "tests/phpt/manifests/full-known-failures.jsonl",
        planned_solution_layer: "PHPT triage and module ownership",
    },
    KnownGapSpec {
        id: "unsupported-section",
        title: "Unsupported PHPT section",
        reference_behavior: "run-tests.php understands the section and prepares the target invocation accordingly.",
        current_rust_behavior: "The local PHPT runner BORKs because the section is unsupported.",
        fixture_or_phpt_example: "ext/standard/tests/basic/bug.phpt",
        planned_solution_layer: "php_phpt_tools runner section handling",
    },
    KnownGapSpec {
        id: "missing-target-cli-capability",
        title: "Missing target CLI capability",
        reference_behavior: "The upstream target supports CLI/SAPI-specific invocation required by the PHPT.",
        current_rust_behavior: "The current target mode cannot emulate phpdbg, CGI, or another required SAPI capability.",
        fixture_or_phpt_example: "sapi/phpdbg/tests/print_001.phpt",
        planned_solution_layer: "target CLI/SAPI policy or explicit extension policy",
    },
    KnownGapSpec {
        id: "unsupported-file-external",
        title: "Unsupported FILE_EXTERNAL",
        reference_behavior: "run-tests.php loads the external FILE payload and executes it as the test script.",
        current_rust_behavior: "The runner marks the PHPT BORK because safe FILE_EXTERNAL support is not complete.",
        fixture_or_phpt_example: "ext/standard/tests/file/bug45181.phpt",
        planned_solution_layer: "php_phpt_tools runner file materialization",
    },
    KnownGapSpec {
        id: "unsupported-expectation",
        title: "Unsupported expectation variant",
        reference_behavior: "run-tests.php compares output with the declared expectation section.",
        current_rust_behavior: "The runner BORKs because this expectation form is not yet supported or normalized.",
        fixture_or_phpt_example: "ext/standard/tests/general_functions/bug.phpt",
        planned_solution_layer: "php_phpt_tools expectation matcher",
    },
    KnownGapSpec {
        id: "unsupported-runner-io",
        title: "Unsupported runner IO setup",
        reference_behavior: "run-tests.php passes ARGS, STDIN, ENV, INI, CLEAN, or related IO setup to the target.",
        current_rust_behavior: "The local runner cannot yet reproduce that setup for this PHPT.",
        fixture_or_phpt_example: "ext/standard/tests/streams/bug.phpt",
        planned_solution_layer: "php_phpt_tools runner environment and process setup",
    },
    KnownGapSpec {
        id: "malformed-or-non-utf8-phpt",
        title: "Malformed or non-UTF8 PHPT source",
        reference_behavior: "run-tests.php either parses the PHPT with PHP's file handling or reports a deterministic BORK.",
        current_rust_behavior: "The local runner classifies the PHPT as malformed or lossy/non-UTF8 input.",
        fixture_or_phpt_example: "tests/phpt/manifests/full-known-failures.jsonl",
        planned_solution_layer: "php_phpt_tools parser and source decoding",
    },
    KnownGapSpec {
        id: "malformed-or-incomplete-phpt",
        title: "Malformed or incomplete PHPT",
        reference_behavior: "run-tests.php reports malformed PHPT structure consistently.",
        current_rust_behavior: "The local runner classifies missing required sections as BORK.",
        fixture_or_phpt_example: "tests/phpt/manifests/full-known-failures.jsonl",
        planned_solution_layer: "php_phpt_tools PHPT parser diagnostics",
    },
    KnownGapSpec {
        id: "unknown-bork",
        title: "Unknown BORK",
        reference_behavior: "run-tests.php gives a concrete reason why the PHPT cannot be executed.",
        current_rust_behavior: "The local baseline retained a BORK without a more specific subclass.",
        fixture_or_phpt_example: "tests/phpt/manifests/full-baseline-module-counts.jsonl",
        planned_solution_layer: "PHPT triage subclass refinement",
    },
    KnownGapSpec {
        id: "other-bork",
        title: "Other BORK",
        reference_behavior: "run-tests.php gives a concrete reason why the PHPT cannot be executed.",
        current_rust_behavior: "The local baseline groups a low-volume BORK outside the named subclasses.",
        fixture_or_phpt_example: "tests/phpt/manifests/full-baseline-module-counts.jsonl",
        planned_solution_layer: "PHPT triage subclass refinement",
    },
];

pub(super) const MODULE_PLAN: &[ModulePlanSpec] = &[
    ModulePlanSpec {
        name: "phpt.foundation",
        scope: &[
            "baseline metadata",
            "source integrity",
            "full-regression bookkeeping",
        ],
        non_scope: &["runtime semantics", "standard library behavior"],
        source_places: &["scripts/phpt/", "crates/php_phpt_tools/"],
        target_gates: &["nix develop -c just verify-phpt"],
        next_step: "Keep committed baseline, corpus, and source-integrity manifests consistent.",
        leverage: 100,
    },
    ModulePlanSpec {
        name: "phpt.runner",
        scope: &[
            "PHPT section handling",
            "expectation matching",
            "runner BORK reduction",
        ],
        non_scope: &["VM feature implementation"],
        source_places: &["crates/php_phpt_tools/src/", "scripts/phpt/"],
        target_gates: &["nix develop -c just phpt-runner-smoke"],
        next_step: "Reduce runner-owned BORKs before attributing failures to the engine.",
        leverage: 98,
    },
    ModulePlanSpec {
        name: "phpt.cli",
        scope: &[
            "target binary discovery",
            "PHP CLI compatible invocation",
            "argv/stdin/ini plumbing",
        ],
        non_scope: &["full SAPI emulation", "CGI/FPM behavior"],
        source_places: &["crates/php_vm_cli/", "scripts/phpt/"],
        target_gates: &["nix develop -c just phpt-target-smoke"],
        next_step: "Keep target invocation deterministic for upstream PHPT execution.",
        leverage: 96,
    },
    ModulePlanSpec {
        name: "zend.basic",
        scope: &[
            "top-level execution",
            "scalar literals",
            "numeric literal separators",
            "echo",
            "print",
            "statement sequencing",
            "top-level return",
            "top-level exit",
            "basic var_dump output",
        ],
        non_scope: &[
            "dynamic variables",
            "objects",
            "extensions",
            "advanced type system",
            "exact string-to-float formatting edge cases",
        ],
        source_places: &["Zend/tests/", "crates/php_vm/", "crates/php_runtime/"],
        target_gates: &["nix develop -c just phpt-module MODULE=zend.basic"],
        next_step: "Keep the selected zend.basic gate green while later modules expand runtime semantics.",
        leverage: 94,
    },
    ModulePlanSpec {
        name: "operators.conversions",
        scope: &[
            "arithmetic",
            "bitwise operators",
            "comparison",
            "boolean conversion",
            "numeric-string conversion",
            "concat",
            "assignment operators",
            "increment/decrement",
            "leading numeric string warnings",
            "object numeric casts",
        ],
        non_scope: &[
            "array union semantics",
            "array/object concat beyond __toString smoke coverage",
            "full TypeError/Throwable catch semantics for non-numeric operands",
            "pipe operator",
            "nullsafe operator",
            "property hooks",
            "fiber error suppression",
            "performance-only concat stress",
        ],
        source_places: &["Zend/tests/", "crates/php_runtime/", "crates/php_vm/"],
        target_gates: &["nix develop -c just phpt-module MODULE=operators.conversions"],
        next_step: "Keep the selected scalar conversion gate green while later modules expand arrays, objects, and diagnostics.",
        leverage: 92,
    },
    ModulePlanSpec {
        name: "diagnostics.output",
        scope: &[
            "warnings",
            "notices",
            "fatal formatting",
            "display_errors",
            "output channels",
        ],
        non_scope: &["exact wording for intentionally unsupported extensions"],
        source_places: &["crates/php_runtime/", "crates/php_vm/"],
        target_gates: &["nix develop -c just verify-runtime"],
        next_step: "Centralize runtime diagnostic rendering and continuation semantics.",
        leverage: 90,
    },
    ModulePlanSpec {
        name: "strings.literals",
        scope: &[
            "string literal decoding",
            "heredoc/nowdoc",
            "string interpolation basics",
        ],
        non_scope: &["full ext/standard string API"],
        source_places: &[
            "crates/php_lexer/",
            "crates/php_syntax/",
            "crates/php_runtime/",
        ],
        target_gates: &["nix develop -c just verify-frontend"],
        next_step: "Separate frontend literal gaps from runtime string builtin gaps.",
        leverage: 88,
    },
    ModulePlanSpec {
        name: "arrays.references",
        scope: &[
            "ordered arrays",
            "key conversion",
            "references",
            "copy-on-write",
            "foreach",
        ],
        non_scope: &["SPL collection classes"],
        source_places: &["crates/php_runtime/", "crates/php_vm/"],
        target_gates: &["nix develop -c just phpt-module MODULE=standard.arrays"],
        next_step: "Close array data-model and reference/COW gaps before array builtins.",
        leverage: 86,
    },
    ModulePlanSpec {
        name: "zend.functions",
        scope: &[
            "user functions",
            "closures",
            "callables",
            "arity",
            "type coercion",
        ],
        non_scope: &["Reflection API surface"],
        source_places: &[
            "crates/php_semantics/",
            "crates/php_runtime/",
            "crates/php_vm/",
        ],
        target_gates: &["nix develop -c just phpt-module MODULE=zend.functions"],
        next_step: "Use generated arginfo for builtin arity and parameter metadata.",
        leverage: 84,
    },
    ModulePlanSpec {
        name: "objects.classes",
        scope: &[
            "classes",
            "properties",
            "methods",
            "visibility",
            "magic",
            "traits",
            "enums",
        ],
        non_scope: &["Reflection API completion"],
        source_places: &[
            "crates/php_semantics/",
            "crates/php_runtime/",
            "crates/php_vm/",
        ],
        target_gates: &["nix develop -c just phpt-module MODULE=zend.objects"],
        next_step: "Stabilize constructor/property/method basics before magic behavior.",
        leverage: 82,
    },
    ModulePlanSpec {
        name: "filesystem.streams",
        scope: &[
            "local filesystem",
            "streams",
            "resources",
            "include_path",
            "include/require",
        ],
        non_scope: &["network streams", "PHAR streams"],
        source_places: &[
            "ext/standard/tests/file/",
            "ext/standard/tests/streams/",
            "crates/php_runtime/",
        ],
        target_gates: &["nix develop -c just phpt-module MODULE=filesystem.streams"],
        next_step: "Keep filesystem policy root-constrained and deterministic.",
        leverage: 80,
    },
    ModulePlanSpec {
        name: "standard.arrays",
        scope: &["ext/standard array builtins"],
        non_scope: &["array COW engine work"],
        source_places: &["ext/standard/tests/array/"],
        target_gates: &["nix develop -c just phpt-module MODULE=standard.arrays"],
        next_step: "Implement array builtins after array data model gaps are closed.",
        leverage: 78,
    },
    ModulePlanSpec {
        name: "standard.strings",
        scope: &["ext/standard string builtins"],
        non_scope: &["frontend literal decoding"],
        source_places: &["ext/standard/tests/strings/", "tests/strings/"],
        target_gates: &["nix develop -c just phpt-module MODULE=standard.strings"],
        next_step: "Close common binary-safe string functions against Reference PHP.",
        leverage: 76,
    },
    ModulePlanSpec {
        name: "standard.math",
        scope: &["math and numeric standard builtins"],
        non_scope: &["operator conversion semantics"],
        source_places: &["ext/standard/tests/math/"],
        target_gates: &["nix develop -c just phpt-module MODULE=standard.math"],
        next_step: "Use php-src arginfo and Reference PHP for edge-case numeric behavior.",
        leverage: 74,
    },
    ModulePlanSpec {
        name: "standard.variables",
        scope: &["variable inspection and conversion builtins"],
        non_scope: &["general VM symbol-table redesign"],
        source_places: &[
            "ext/standard/tests/general_functions/",
            "ext/standard/tests/array/",
        ],
        target_gates: &["nix develop -c just phpt-module MODULE=standard.variables"],
        next_step: "Stabilize var_dump/print_r/serialization-adjacent value rendering.",
        leverage: 72,
    },
    ModulePlanSpec {
        name: "standard.serialization",
        scope: &["serialize", "unserialize", "value persistence"],
        non_scope: &["session module persistence"],
        source_places: &["ext/standard/tests/serialize/"],
        target_gates: &["nix develop -c just phpt-module MODULE=standard.serialization"],
        next_step: "Implement serialization after arrays/objects are stable.",
        leverage: 70,
    },
    ModulePlanSpec {
        name: "json",
        scope: &["json_encode", "json_decode", "json last-error state"],
        non_scope: &["full JsonSerializable without object model readiness"],
        source_places: &["ext/json/tests/"],
        target_gates: &["nix develop -c just phpt-module MODULE=json"],
        next_step: "Close request-local JSON error state and common flags.",
        leverage: 68,
    },
    ModulePlanSpec {
        name: "pcre",
        scope: &["preg_* builtins backed by PCRE2"],
        non_scope: &["PCRE JIT/callout parity"],
        source_places: &["ext/pcre/tests/"],
        target_gates: &["nix develop -c just phpt-module MODULE=pcre"],
        next_step: "Use PCRE2 while documenting unsupported modifier/callout gaps.",
        leverage: 66,
    },
    ModulePlanSpec {
        name: "date",
        scope: &["date/time builtins and DateTime MVP"],
        non_scope: &["complete timelib natural-language parity"],
        source_places: &["ext/date/tests/"],
        target_gates: &["nix develop -c just phpt-module MODULE=date"],
        next_step: "Stabilize timezone persistence and common formatting/parsing.",
        leverage: 64,
    },
    ModulePlanSpec {
        name: "spl",
        scope: &["core SPL interfaces and common collections"],
        non_scope: &["full SPL API parity"],
        source_places: &["ext/spl/tests/"],
        target_gates: &["nix develop -c just phpt-module MODULE=spl"],
        next_step: "Build on stable object, array, iterator, and filesystem layers.",
        leverage: 62,
    },
    ModulePlanSpec {
        name: "reflection",
        scope: &["Reflection metadata for functions, classes, methods, properties, attributes"],
        non_scope: &["fake metadata not backed by frontend/runtime/arginfo"],
        source_places: &["ext/reflection/tests/"],
        target_gates: &["nix develop -c just phpt-module MODULE=reflection"],
        next_step: "Expose generated arginfo and semantic metadata through Reflection APIs.",
        leverage: 60,
    },
    ModulePlanSpec {
        name: "extension.policy",
        scope: &[
            "non-core extension classification",
            "must-fix vs optional/out-of-scope routing",
        ],
        non_scope: &["large extension implementation"],
        source_places: &[
            "ext/dom/",
            "ext/xml/",
            "ext/soap/",
            "ext/intl/",
            "ext/gd/",
            "ext/opcache/",
        ],
        target_gates: &["nix develop -c just phpt-triage"],
        next_step: "Classify extension failures without hiding them from full regression.",
        leverage: 58,
    },
];
