#!/usr/bin/env python3
"""Generate lexer fixture token coverage from the pinned PHP oracle."""

from __future__ import annotations

import collections
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
FIXTURE_DIR = ROOT / "tests" / "fixtures" / "lexer"
TOKENIZE_SCRIPT = ROOT / "scripts" / "tokenize-reference.php"
DUMP_SCRIPT = ROOT / "scripts" / "dump-reference-tokens.php"
OUTPUT = ROOT / "docs" / "phase-1" / "token-coverage.generated.md"
PINNED_PHP = ROOT / "third_party" / "php-src" / "sapi" / "cli" / "php"

PARSER_CONTEXTUAL = {
    "T_ENUM",
    "T_MATCH",
    "T_NAME_FULLY_QUALIFIED",
    "T_NAME_QUALIFIED",
    "T_NAME_RELATIVE",
    "T_READONLY",
}

EXTENSION_OR_CONFIG_DEPENDENT = {
    "T_OPEN_TAG_WITH_ECHO",
}

DEPRECATED_OR_ALIAS = {
    "T_PAAMAYIM_NEKUDOTAYIM",
}


def find_php() -> str | None:
    env_php = os.environ.get("REFERENCE_PHP")
    if env_php:
        return env_php
    if PINNED_PHP.exists() and os.access(PINNED_PHP, os.X_OK):
        return str(PINNED_PHP)
    return shutil.which("php")


def run_json(command: list[str]) -> dict:
    completed = subprocess.run(
        command,
        cwd=ROOT,
        check=True,
        text=True,
        capture_output=True,
    )
    return json.loads(completed.stdout)


def status_for(token: str, covered: bool) -> str:
    if covered:
        return "covered"
    if token in PARSER_CONTEXTUAL:
        return "parser-contextual"
    if token in EXTENSION_OR_CONFIG_DEPENDENT:
        return "extension/config-dependent"
    if token in DEPRECATED_OR_ALIAS:
        return "deprecated/alias"
    return "not-yet-covered"


def markdown_escape(text: str) -> str:
    return text.replace("|", "\\|")


def write_report(
    dump: dict,
    coverage: dict[str, set[str]],
    fixtures: list[Path],
) -> None:
    token_names = [row["name"] for row in dump["tokens"]]
    counts = collections.Counter(
        status_for(token, token in coverage) for token in token_names
    )

    lines = [
        "# Generated Token Coverage",
        "",
        "Generated by `scripts/collect-lexer-fixtures.py` from the PHP reference oracle.",
        "Do not edit this file by hand.",
        "",
        f"- PHP version: `{dump['php_version']}`",
        f"- PHP token constants: `{len(token_names)}`",
        f"- Lexer fixtures scanned: `{len(fixtures)}`",
        "",
        "## Status Counts",
        "",
        "| Status | Count |",
        "| --- | ---: |",
    ]

    for status in [
        "covered",
        "not-yet-covered",
        "parser-contextual",
        "extension/config-dependent",
        "deprecated/alias",
    ]:
        lines.append(f"| {status} | {counts.get(status, 0)} |")

    lines.extend(
        [
            "",
            "## Token Matrix",
            "",
            "| Token | Status | Fixtures |",
            "| --- | --- | --- |",
        ]
    )

    for token in token_names:
        fixture_names = sorted(coverage.get(token, set()))
        fixtures_cell = "<br>".join(markdown_escape(name) for name in fixture_names) or "-"
        status = status_for(token, bool(fixture_names))
        lines.append(f"| `{token}` | {status} | {fixtures_cell} |")

    lines.extend(
        [
            "",
            "## Notes",
            "",
            "- `covered` means the token appears in at least one reference-tokenized fixture.",
            "- `not-yet-covered` is explicit remaining fixture work, not a claim that the Rust lexer implements the token.",
            "- `parser-contextual` tokens may depend on `TOKEN_PARSE` or parser-adjacent PHP context and are not hard-gated by Phase 1.",
            "- `extension/config-dependent` tokens require runtime configuration or source forms that are tracked separately.",
        ]
    )

    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    php = find_php()
    if php is None:
        print(
            "[skip] no PHP binary found; set REFERENCE_PHP or build the pinned reference",
            file=sys.stderr,
        )
        print("[skip] token coverage was not computed", file=sys.stderr)
        return 0

    fixtures = sorted(FIXTURE_DIR.glob("*.php"))
    if not fixtures:
        print(f"[fail] no lexer fixtures found in {FIXTURE_DIR}", file=sys.stderr)
        return 1

    try:
        dump = run_json([php, str(DUMP_SCRIPT)])
    except (subprocess.CalledProcessError, json.JSONDecodeError) as error:
        print(f"[fail] failed to dump reference tokens: {error}", file=sys.stderr)
        return 1

    coverage: dict[str, set[str]] = collections.defaultdict(set)
    for fixture in fixtures:
        try:
            token_stream = run_json([php, str(TOKENIZE_SCRIPT), "--file", str(fixture)])
        except (subprocess.CalledProcessError, json.JSONDecodeError) as error:
            print(f"[fail] failed to tokenize {fixture}: {error}", file=sys.stderr)
            return 1

        rel = str(fixture.relative_to(ROOT))
        for token in token_stream.get("tokens", []):
            kind = token.get("kind")
            if isinstance(kind, str) and kind.startswith("T_"):
                coverage[kind].add(rel)

    write_report(dump, coverage, fixtures)
    print(f"[ok] wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
