//! Canonical native-engine telemetry collected only when explicitly enabled.

use std::collections::BTreeMap;

/// One native compilation record suitable for diagnostics and profiles.
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct NativeCompileDescriptor {
    pub function_id: u32,
    pub function_name: String,
    pub ir_fingerprint: String,
    pub code_bytes: u64,
    pub compile_time_nanos: u64,
    pub target_isa: String,
    pub runtime_abi_hash: u64,
    pub helper_abi_hash: u64,
    pub config_hash: u64,
}

/// Product telemetry for the single mandatory native engine.
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct VmCounters {
    pub native_compile_attempts: u64,
    pub native_compile_successes: u64,
    pub native_compile_failures: u64,
    pub native_compile_time_nanos: u64,
    pub native_compile_code_bytes: u64,
    pub native_compile_descriptors: Vec<NativeCompileDescriptor>,

    pub native_cache_hits: u64,
    pub native_cache_misses: u64,
    pub native_cache_writes: u64,
    pub native_cache_rebuilds: u64,
    pub native_cache_invalid_artifacts: u64,
    pub native_cache_compile_waits: u64,
    pub native_cache_evictions: u64,
    pub native_cache_bytes_loaded: u64,
    pub native_cache_bytes_written: u64,

    pub native_execution_entries: u64,
    pub native_execution_time_nanos: u64,
    pub native_region_entries: u64,
    pub native_region_side_exits: u64,
    pub native_region_side_exits_by_reason: BTreeMap<String, u64>,
    pub native_call_direct: u64,
    pub native_call_dynamic: u64,
    pub native_callsite_total: u64,
    pub native_same_unit_direct_eligible: u64,
    pub native_same_unit_direct_executed: u64,
    pub native_cross_unit_direct_eligible: u64,
    pub native_cross_unit_direct_executed: u64,
    pub native_method_monomorphic_eligible: u64,
    pub native_method_monomorphic_executed: u64,
    pub native_builtin_direct_eligible: u64,
    pub native_builtin_direct_executed: u64,
    pub native_builtin_calls_by_name: BTreeMap<String, u64>,
    pub native_builtin_time_nanos_by_name: BTreeMap<String, u64>,
    pub native_call_dynamic_by_reason: BTreeMap<String, u64>,
    pub native_call_dynamic_by_target: BTreeMap<String, u64>,
    pub native_callsite_calls_by_id: BTreeMap<String, u64>,
    pub native_callsite_inclusive_time_nanos_by_id: BTreeMap<String, u64>,
    pub native_callsite_exclusive_time_nanos_by_id: BTreeMap<String, u64>,
    pub native_call_argument_allocation_bytes: u64,
    pub native_call_frame_bytes: u64,
    pub native_function_body_compile_count: u64,
    pub native_duplicate_function_body_count: u64,
    pub native_code_bytes_by_function: BTreeMap<String, u64>,
    pub native_code_bytes_by_unit: BTreeMap<String, u64>,
    pub native_stack_bytes_by_function: BTreeMap<String, u64>,
    pub native_rodata_bytes: u64,
    pub native_relocation_bytes: u64,
    pub native_metadata_bytes: u64,
    pub native_artifact_header_padding_bytes: u64,
    pub native_mapped_executable_bytes: u64,
    pub native_loaded_artifact_registry_hits: u64,
    pub native_loaded_artifact_maps: u64,
    pub native_loaded_entry_table_constructions: u64,
    pub native_worker_stack_virtual_bytes: u64,
    pub native_worker_stack_committed_bytes: u64,
    pub native_frame_arena_capacity_bytes: u64,
    pub native_frame_arena_high_water_bytes: u64,
    pub native_inlined_calls: u64,
    pub native_inline_bytes_added: u64,
    pub native_inline_calls_removed: u64,
    pub native_tail_calls: u64,
    pub native_inline_rejected_by_reason: BTreeMap<String, u64>,
    pub native_version_published: u64,
    pub native_version_retired: u64,
    pub native_transition_count: u64,
    pub native_transition_by_reason: BTreeMap<String, u64>,
    pub native_transition_time_nanos: u64,
    pub native_transition_time_nanos_by_reason: BTreeMap<String, u64>,
    pub runtime_helper_calls: u64,
    pub runtime_helper_calls_by_id: BTreeMap<String, u64>,
    pub runtime_helper_time_nanos: u64,
    pub runtime_helper_time_nanos_by_id: BTreeMap<String, u64>,
    pub runtime_helper_calls_by_ir_operation: BTreeMap<String, u64>,
    pub runtime_helper_time_nanos_by_ir_operation: BTreeMap<String, u64>,
    pub runtime_helper_calls_by_function: BTreeMap<String, u64>,
    pub runtime_helper_time_nanos_by_function: BTreeMap<String, u64>,
    pub runtime_helper_local_read_by_reason: BTreeMap<String, u64>,
    pub runtime_helper_local_store_by_reason: BTreeMap<String, u64>,
    pub runtime_helper_reference_read_by_value_class: BTreeMap<String, u64>,
    pub runtime_helper_truthy_by_value_class: BTreeMap<String, u64>,
    pub runtime_helper_retain_by_reason: BTreeMap<String, u64>,
    pub runtime_helper_release_by_reason: BTreeMap<String, u64>,
    pub runtime_helper_release_to_zero: u64,
    pub runtime_helper_inclusive_time_nanos_by_id: BTreeMap<String, u64>,
    pub runtime_helper_object_release_fast_paths: u64,
    pub runtime_helper_object_release_root_scans: u64,
    pub runtime_helper_object_release_root_scans_by_reason: BTreeMap<String, u64>,
    pub native_value_encodes: u64,
    pub native_value_decodes: u64,
    pub native_value_table_allocations: u64,
    pub native_value_table_reuses: u64,
    pub native_value_table_high_water: u64,
    pub native_value_table_materializations_by_kind_and_origin: BTreeMap<String, u64>,
    pub native_ssa_promoted_locals: u64,
    pub native_ssa_promoted_registers: u64,
    pub native_ownership_moves: u64,
    pub native_ownership_clones: u64,
    pub native_ownership_escapes: u64,
    pub native_slow_path_entries_by_reason: BTreeMap<String, u64>,
    pub gc_safepoint_polls: u64,
    pub gc_safepoint_collections: u64,
}

impl VmCounters {
    #[must_use]
    pub fn to_json(&self) -> String {
        format!(
            concat!(
                "{{\n",
                "  \"schema_version\": 13,\n",
                "  \"native_compile_attempts\": {},\n",
                "  \"native_compile_successes\": {},\n",
                "  \"native_compile_failures\": {},\n",
                "  \"native_compile_time_nanos\": {},\n",
                "  \"native_compile_code_bytes\": {},\n",
                "  \"native_cache_hits\": {},\n",
                "  \"native_cache_misses\": {},\n",
                "  \"native_cache_writes\": {},\n",
                "  \"native_cache_rebuilds\": {},\n",
                "  \"native_cache_invalid_artifacts\": {},\n",
                "  \"native_cache_compile_waits\": {},\n",
                "  \"native_cache_evictions\": {},\n",
                "  \"native_cache_bytes_loaded\": {},\n",
                "  \"native_cache_bytes_written\": {},\n",
                "  \"native_execution_entries\": {},\n",
                "  \"native_execution_time_nanos\": {},\n",
                "  \"native_region_entries\": {},\n",
                "  \"native_region_side_exits\": {},\n",
                "  \"native_region_side_exits_by_reason\": {},\n",
                "  \"native_call_direct\": {},\n",
                "  \"native_call_dynamic\": {},\n",
                "  \"native_callsite_total\": {},\n",
                "  \"native_same_unit_direct_eligible\": {},\n",
                "  \"native_same_unit_direct_executed\": {},\n",
                "  \"native_cross_unit_direct_eligible\": {},\n",
                "  \"native_cross_unit_direct_executed\": {},\n",
                "  \"native_method_monomorphic_eligible\": {},\n",
                "  \"native_method_monomorphic_executed\": {},\n",
                "  \"native_builtin_direct_eligible\": {},\n",
                "  \"native_builtin_direct_executed\": {},\n",
                "  \"native_builtin_calls_by_name\": {},\n",
                "  \"native_builtin_time_nanos_by_name\": {},\n",
                "  \"native_call_dynamic_by_reason\": {},\n",
                "  \"native_call_dynamic_by_target\": {},\n",
                "  \"native_callsite_calls_by_id\": {},\n",
                "  \"native_callsite_inclusive_time_nanos_by_id\": {},\n",
                "  \"native_callsite_exclusive_time_nanos_by_id\": {},\n",
                "  \"native_call_argument_allocation_bytes\": {},\n",
                "  \"native_call_frame_bytes\": {},\n",
                "  \"native_function_body_compile_count\": {},\n",
                "  \"native_duplicate_function_body_count\": {},\n",
                "  \"native_code_bytes_by_function\": {},\n",
                "  \"native_code_bytes_by_unit\": {},\n",
                "  \"native_stack_bytes_by_function\": {},\n",
                "  \"native_rodata_bytes\": {},\n",
                "  \"native_relocation_bytes\": {},\n",
                "  \"native_metadata_bytes\": {},\n",
                "  \"native_artifact_header_padding_bytes\": {},\n",
                "  \"native_mapped_executable_bytes\": {},\n",
                "  \"native_loaded_artifact_registry_hits\": {},\n",
                "  \"native_loaded_artifact_maps\": {},\n",
                "  \"native_loaded_entry_table_constructions\": {},\n",
                "  \"native_worker_stack_virtual_bytes\": {},\n",
                "  \"native_worker_stack_committed_bytes\": {},\n",
                "  \"native_frame_arena_capacity_bytes\": {},\n",
                "  \"native_frame_arena_high_water_bytes\": {},\n",
                "  \"native_inlined_calls\": {},\n",
                "  \"native_inline_bytes_added\": {},\n",
                "  \"native_inline_calls_removed\": {},\n",
                "  \"native_tail_calls\": {},\n",
                "  \"native_inline_rejected_by_reason\": {},\n",
                "  \"native_version_published\": {},\n",
                "  \"native_version_retired\": {},\n",
                "  \"native_transition_count\": {},\n",
                "  \"native_transition_by_reason\": {},\n",
                "  \"native_transition_time_nanos\": {},\n",
                "  \"native_transition_time_nanos_by_reason\": {},\n",
                "  \"runtime_helper_calls\": {},\n",
                "  \"runtime_helper_calls_by_id\": {},\n",
                "  \"runtime_helper_time_nanos\": {},\n",
                "  \"runtime_helper_time_nanos_by_id\": {},\n",
                "  \"runtime_helper_calls_by_ir_operation\": {},\n",
                "  \"runtime_helper_time_nanos_by_ir_operation\": {},\n",
                "  \"runtime_helper_calls_by_function\": {},\n",
                "  \"runtime_helper_time_nanos_by_function\": {},\n",
                "  \"runtime_helper_local_read_by_reason\": {},\n",
                "  \"runtime_helper_local_store_by_reason\": {},\n",
                "  \"runtime_helper_reference_read_by_value_class\": {},\n",
                "  \"runtime_helper_truthy_by_value_class\": {},\n",
                "  \"runtime_helper_retain_by_reason\": {},\n",
                "  \"runtime_helper_release_by_reason\": {},\n",
                "  \"runtime_helper_release_to_zero\": {},\n",
                "  \"runtime_helper_inclusive_time_nanos_by_id\": {},\n",
                "  \"runtime_helper_object_release_fast_paths\": {},\n",
                "  \"runtime_helper_object_release_root_scans\": {},\n",
                "  \"runtime_helper_object_release_root_scans_by_reason\": {},\n",
                "  \"native_value_encodes\": {},\n",
                "  \"native_value_decodes\": {},\n",
                "  \"native_value_table_allocations\": {},\n",
                "  \"native_value_table_reuses\": {},\n",
                "  \"native_value_table_high_water\": {},\n",
                "  \"native_value_table_materializations_by_kind_and_origin\": {},\n",
                "  \"native_ssa_promoted_locals\": {},\n",
                "  \"native_ssa_promoted_registers\": {},\n",
                "  \"native_ownership_moves\": {},\n",
                "  \"native_ownership_clones\": {},\n",
                "  \"native_ownership_escapes\": {},\n",
                "  \"native_slow_path_entries_by_reason\": {},\n",
                "  \"gc_safepoint_polls\": {},\n",
                "  \"gc_safepoint_collections\": {}\n",
                "}}\n"
            ),
            self.native_compile_attempts,
            self.native_compile_successes,
            self.native_compile_failures,
            self.native_compile_time_nanos,
            self.native_compile_code_bytes,
            self.native_cache_hits,
            self.native_cache_misses,
            self.native_cache_writes,
            self.native_cache_rebuilds,
            self.native_cache_invalid_artifacts,
            self.native_cache_compile_waits,
            self.native_cache_evictions,
            self.native_cache_bytes_loaded,
            self.native_cache_bytes_written,
            self.native_execution_entries,
            self.native_execution_time_nanos,
            self.native_region_entries,
            self.native_region_side_exits,
            counter_map_json(&self.native_region_side_exits_by_reason),
            self.native_call_direct,
            self.native_call_dynamic,
            self.native_callsite_total,
            self.native_same_unit_direct_eligible,
            self.native_same_unit_direct_executed,
            self.native_cross_unit_direct_eligible,
            self.native_cross_unit_direct_executed,
            self.native_method_monomorphic_eligible,
            self.native_method_monomorphic_executed,
            self.native_builtin_direct_eligible,
            self.native_builtin_direct_executed,
            counter_map_json(&self.native_builtin_calls_by_name),
            counter_map_json(&self.native_builtin_time_nanos_by_name),
            counter_map_json(&self.native_call_dynamic_by_reason),
            counter_map_json(&self.native_call_dynamic_by_target),
            counter_map_json(&self.native_callsite_calls_by_id),
            counter_map_json(&self.native_callsite_inclusive_time_nanos_by_id),
            counter_map_json(&self.native_callsite_exclusive_time_nanos_by_id),
            self.native_call_argument_allocation_bytes,
            self.native_call_frame_bytes,
            self.native_function_body_compile_count,
            self.native_duplicate_function_body_count,
            counter_map_json(&self.native_code_bytes_by_function),
            counter_map_json(&self.native_code_bytes_by_unit),
            counter_map_json(&self.native_stack_bytes_by_function),
            self.native_rodata_bytes,
            self.native_relocation_bytes,
            self.native_metadata_bytes,
            self.native_artifact_header_padding_bytes,
            self.native_mapped_executable_bytes,
            self.native_loaded_artifact_registry_hits,
            self.native_loaded_artifact_maps,
            self.native_loaded_entry_table_constructions,
            self.native_worker_stack_virtual_bytes,
            self.native_worker_stack_committed_bytes,
            self.native_frame_arena_capacity_bytes,
            self.native_frame_arena_high_water_bytes,
            self.native_inlined_calls,
            self.native_inline_bytes_added,
            self.native_inline_calls_removed,
            self.native_tail_calls,
            counter_map_json(&self.native_inline_rejected_by_reason),
            self.native_version_published,
            self.native_version_retired,
            self.native_transition_count,
            counter_map_json(&self.native_transition_by_reason),
            self.native_transition_time_nanos,
            counter_map_json(&self.native_transition_time_nanos_by_reason),
            self.runtime_helper_calls,
            counter_map_json(&self.runtime_helper_calls_by_id),
            self.runtime_helper_time_nanos,
            counter_map_json(&self.runtime_helper_time_nanos_by_id),
            counter_map_json(&self.runtime_helper_calls_by_ir_operation),
            counter_map_json(&self.runtime_helper_time_nanos_by_ir_operation),
            counter_map_json(&self.runtime_helper_calls_by_function),
            counter_map_json(&self.runtime_helper_time_nanos_by_function),
            counter_map_json(&self.runtime_helper_local_read_by_reason),
            counter_map_json(&self.runtime_helper_local_store_by_reason),
            counter_map_json(&self.runtime_helper_reference_read_by_value_class),
            counter_map_json(&self.runtime_helper_truthy_by_value_class),
            counter_map_json(&self.runtime_helper_retain_by_reason),
            counter_map_json(&self.runtime_helper_release_by_reason),
            self.runtime_helper_release_to_zero,
            counter_map_json(&self.runtime_helper_inclusive_time_nanos_by_id),
            self.runtime_helper_object_release_fast_paths,
            self.runtime_helper_object_release_root_scans,
            counter_map_json(&self.runtime_helper_object_release_root_scans_by_reason),
            self.native_value_encodes,
            self.native_value_decodes,
            self.native_value_table_allocations,
            self.native_value_table_reuses,
            self.native_value_table_high_water,
            counter_map_json(&self.native_value_table_materializations_by_kind_and_origin),
            self.native_ssa_promoted_locals,
            self.native_ssa_promoted_registers,
            self.native_ownership_moves,
            self.native_ownership_clones,
            self.native_ownership_escapes,
            counter_map_json(&self.native_slow_path_entries_by_reason),
            self.gc_safepoint_polls,
            self.gc_safepoint_collections,
        )
    }
}

fn counter_map_json(values: &BTreeMap<String, u64>) -> String {
    let entries = values
        .iter()
        .map(|(name, value)| format!("\"{}\":{value}", json_escape(name)))
        .collect::<Vec<_>>()
        .join(",");
    format!("{{{entries}}}")
}

fn json_escape(value: &str) -> String {
    let mut escaped = String::with_capacity(value.len());
    for character in value.chars() {
        match character {
            '\"' => escaped.push_str("\\\""),
            '\\' => escaped.push_str("\\\\"),
            '\n' => escaped.push_str("\\n"),
            '\r' => escaped.push_str("\\r"),
            '\t' => escaped.push_str("\\t"),
            character if character.is_control() => {
                use std::fmt::Write as _;
                let _ = write!(escaped, "\\u{:04x}", character as u32);
            }
            character => escaped.push(character),
        }
    }
    escaped
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn counter_json_contains_only_native_engine_families() {
        let json = VmCounters::default().to_json();
        for family in [
            "native_compile",
            "native_cache",
            "native_execution",
            "native_region",
            "native_call",
            "native_version",
            "native_transition",
            "runtime_helper",
            "gc_safepoint",
        ] {
            assert!(json.contains(family), "missing {family}: {json}");
        }
    }

    #[test]
    fn counter_json_serializes_helper_breakdowns() {
        let mut counters = VmCounters {
            runtime_helper_calls: 2,
            runtime_helper_time_nanos: 17,
            ..VmCounters::default()
        };
        counters
            .runtime_helper_calls_by_id
            .insert("native_\"binary\"".to_owned(), 2);
        counters
            .runtime_helper_time_nanos_by_id
            .insert("native_\"binary\"".to_owned(), 17);

        let parsed: serde_json::Value = serde_json::from_str(&counters.to_json()).unwrap();
        assert_eq!(parsed["schema_version"], 13);
        assert_eq!(parsed["runtime_helper_calls_by_id"]["native_\"binary\""], 2);
        assert_eq!(
            parsed["runtime_helper_time_nanos_by_id"]["native_\"binary\""],
            17
        );
    }
}
