//! Native/runtime counters collected only when explicitly enabled.

use std::collections::{BTreeMap, BTreeSet};

#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct PropertyFetchProfile {
    pub callsite: String,
    pub property: String,
    pub observations: u64,
    pub receiver_classes: BTreeSet<String>,
    pub class_ids: BTreeSet<u32>,
    pub declared_property_names: BTreeSet<String>,
    pub visibility_contexts: BTreeSet<String>,
    pub property_slot_indexes: BTreeSet<usize>,
    pub class_layout_versions: BTreeSet<u64>,
    pub has_magic_get: bool,
    pub has_property_hook: bool,
    pub dynamic_property_fallback: bool,
    pub saw_declared_visible_property: bool,
    pub saw_uninitialized_typed_property: bool,
    pub non_eligible_reasons: BTreeSet<String>,
}

#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct MethodCallProfile {
    pub callsite: String,
    pub method: String,
    pub observations: u64,
    pub receiver_classes: BTreeSet<String>,
    pub class_ids: BTreeSet<u32>,
    pub declaring_classes: BTreeSet<String>,
    pub method_ids: BTreeSet<u32>,
    pub method_slot_indexes: BTreeSet<usize>,
    pub visibility_contexts: BTreeSet<String>,
    pub override_layout_versions: BTreeSet<u64>,
    pub saw_final_method: bool,
    pub saw_private_method: bool,
    pub saw_static_method: bool,
    pub has_magic_call: bool,
    pub magic_call_fallback: bool,
    pub simple_positional_arguments: bool,
    pub saw_by_ref_argument: bool,
    pub saw_callee_jit_eligible: bool,
    pub saw_direct_vm_call_helper: bool,
    pub non_eligible_reasons: BTreeSet<String>,
}

#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct BoundaryWorkSnapshot {
    pub value_clones: u64,
    pub refcounted_value_clones: u64,
    pub string_allocations: u64,
    pub array_handle_clones: u64,
    pub cow_separations: u64,
    pub reference_cell_creations: u64,
    pub frame_allocations: u64,
    pub frame_reuses: u64,
    pub register_files_allocated: u64,
    pub register_files_reused: u64,
    pub internal_function_dispatches: u64,
    pub symbol_map_lookups: u64,
    pub symbol_linear_fallbacks: u64,
    pub symbol_intern_hits: u64,
    pub symbol_intern_misses: u64,
    pub string_hash_cache_hits: u64,
    pub string_hash_cache_misses: u64,
    pub symbol_eq_fast_hits: u64,
    pub symbol_eq_byte_fallbacks: u64,
    pub array_dim_fetches: u64,
    pub numeric_string_classify_calls: u64,
    pub object_allocations: u64,
    pub property_accesses: u64,
    pub includes: u64,
    pub autoloads: u64,
}

impl BoundaryWorkSnapshot {
    #[must_use]
    pub fn saturating_sub(self, earlier: Self) -> Self {
        macro_rules! sub {
            ($field:ident) => {
                self.$field.saturating_sub(earlier.$field)
            };
        }
        Self {
            value_clones: sub!(value_clones),
            refcounted_value_clones: sub!(refcounted_value_clones),
            string_allocations: sub!(string_allocations),
            array_handle_clones: sub!(array_handle_clones),
            cow_separations: sub!(cow_separations),
            reference_cell_creations: sub!(reference_cell_creations),
            frame_allocations: sub!(frame_allocations),
            frame_reuses: sub!(frame_reuses),
            register_files_allocated: sub!(register_files_allocated),
            register_files_reused: sub!(register_files_reused),
            internal_function_dispatches: sub!(internal_function_dispatches),
            symbol_map_lookups: sub!(symbol_map_lookups),
            symbol_linear_fallbacks: sub!(symbol_linear_fallbacks),
            symbol_intern_hits: sub!(symbol_intern_hits),
            symbol_intern_misses: sub!(symbol_intern_misses),
            string_hash_cache_hits: sub!(string_hash_cache_hits),
            string_hash_cache_misses: sub!(string_hash_cache_misses),
            symbol_eq_fast_hits: sub!(symbol_eq_fast_hits),
            symbol_eq_byte_fallbacks: sub!(symbol_eq_byte_fallbacks),
            array_dim_fetches: sub!(array_dim_fetches),
            numeric_string_classify_calls: sub!(numeric_string_classify_calls),
            object_allocations: sub!(object_allocations),
            property_accesses: sub!(property_accesses),
            includes: sub!(includes),
            autoloads: sub!(autoloads),
        }
    }

    pub fn saturating_add_assign(&mut self, other: Self) {
        macro_rules! add {
            ($field:ident) => {
                self.$field = self.$field.saturating_add(other.$field)
            };
        }
        add!(value_clones);
        add!(refcounted_value_clones);
        add!(string_allocations);
        add!(array_handle_clones);
        add!(cow_separations);
        add!(reference_cell_creations);
        add!(frame_allocations);
        add!(frame_reuses);
        add!(register_files_allocated);
        add!(register_files_reused);
        add!(internal_function_dispatches);
        add!(symbol_map_lookups);
        add!(symbol_linear_fallbacks);
        add!(symbol_intern_hits);
        add!(symbol_intern_misses);
        add!(string_hash_cache_hits);
        add!(string_hash_cache_misses);
        add!(symbol_eq_fast_hits);
        add!(symbol_eq_byte_fallbacks);
        add!(array_dim_fetches);
        add!(numeric_string_classify_calls);
        add!(object_allocations);
        add!(property_accesses);
        add!(includes);
        add!(autoloads);
    }
}

#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct BoundaryProfile {
    pub count: u64,
    pub inclusive_nanos: u64,
    pub exclusive_nanos: u64,
    pub inclusive_native_entries: u64,
    pub exclusive_native_entries: u64,
    pub inclusive_work: BoundaryWorkSnapshot,
    pub exclusive_work: BoundaryWorkSnapshot,
}

#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct OperationProfile {
    pub count: u64,
    pub inclusive_nanos: u64,
}

#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct JitCompileDescriptor {
    pub function_id: u32,
    pub function_name: String,
    pub ir_fingerprint: String,
    pub code_bytes: u64,
    pub compile_time_nanos: u64,
    pub target_isa: String,
    pub abi_hash: u64,
    pub config_hash: u64,
}

#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct VmCounters {
    pub jit_mode: String,
    pub jit_threshold: u64,
    pub include_profiles_by_path: BTreeMap<String, BoundaryProfile>,
    pub optimized_exits_by_reason: BTreeMap<String, u64>,
    pub function_calls: u64,
    pub method_calls: u64,
    pub function_profiles_by_name: BTreeMap<String, BoundaryProfile>,
    pub method_profiles_by_name: BTreeMap<String, BoundaryProfile>,
    pub builtin_profiles_by_name: BTreeMap<String, BoundaryProfile>,
    pub frame_allocations: u64,
    pub frame_reuses: u64,
    pub frames_allocated: u64,
    pub frames_reused: u64,
    pub register_files_allocated: u64,
    pub register_files_reused: u64,
    pub frame_reuse_blocked_by_reason: BTreeMap<String, u64>,
    pub call_frame_layout_observed: BTreeMap<String, u64>,
    pub tiny_frame_candidates: u64,
    pub specialized_frame_hits: u64,
    pub generic_frame_fallback_by_reason: BTreeMap<String, u64>,
    pub arg_array_avoided: u64,
    pub heap_frame_avoided: u64,
    pub frame_alias_state: BTreeMap<String, u64>,
    pub alias_state_transitions: BTreeMap<String, u64>,
    pub fast_path_disabled_by_reference: u64,
    pub ic_invalidated_by_reference: u64,
    pub request_arena_allocations: u64,
    pub request_arena_bytes: u64,
    pub request_pool_resets: u64,
    pub persistent_engine_allocations: u64,
    pub persistent_engine_bytes: u64,
    pub persistent_worker_ic_hits_by_family: BTreeMap<String, u64>,
    pub persistent_worker_ic_misses_by_family: BTreeMap<String, u64>,
    pub persistent_worker_class_cache_hits: u64,
    pub persistent_worker_default_slot_template_hits: u64,
    pub persistent_worker_constructor_hits: u64,
    pub persistent_worker_invalidations_by_reason: BTreeMap<String, u64>,
    pub persistent_worker_request_visible_rejections_by_family: BTreeMap<String, u64>,
    pub arena_fallback_allocations_by_reason: BTreeMap<String, u64>,
    pub destructor_sensitive_arena_blocks: u64,
    pub value_clones: u64,
    pub string_allocations: u64,
    pub array_handle_clones: u64,
    pub cow_separations: u64,
    pub reference_cell_creations: u64,
    pub value_clone_by_kind: BTreeMap<String, u64>,
    pub value_clone_by_source_family: BTreeMap<String, u64>,
    pub value_clone_by_source_family_and_kind: BTreeMap<String, BTreeMap<String, u64>>,
    pub string_allocation_by_source_family: BTreeMap<String, u64>,
    pub array_handle_clone_by_source_family: BTreeMap<String, u64>,
    pub cow_separation_by_source_family: BTreeMap<String, u64>,
    pub reference_cell_creation_by_source_family: BTreeMap<String, u64>,
    pub object_allocations: u64,
    pub array_packed_direct_gets: u64,
    pub array_mixed_indexed_gets: u64,
    pub array_linear_scan_fallbacks: u64,
    pub array_metadata_recomputes: u64,
    pub symbol_map_lookups: u64,
    pub symbol_linear_fallbacks: u64,
    pub symbol_intern_hits: u64,
    pub symbol_intern_misses: u64,
    pub string_hash_cache_hits: u64,
    pub string_hash_cache_misses: u64,
    pub symbol_eq_fast_hits: u64,
    pub symbol_eq_byte_fallbacks: u64,
    pub object_declared_slot_reads: u64,
    pub object_declared_slot_writes: u64,
    pub object_dynamic_property_map_reads: u64,
    pub object_dynamic_property_map_writes: u64,
    pub packed_values_storage_arrays: u64,
    pub packed_values_storage_reads: u64,
    pub packed_values_storage_appends: u64,
    pub packed_virtual_key_iterations: u64,
    pub packed_to_mixed_by_reason: BTreeMap<String, u64>,
    pub record_storage_arrays: u64,
    pub record_slot_reads: u64,
    pub record_slot_writes: u64,
    pub record_shape_promotions: u64,
    pub record_key_symbol_hits: u64,
    pub record_to_mixed_by_reason: BTreeMap<String, u64>,
    pub foreach_no_clone_hits: u64,
    pub foreach_clone_required_by_reason: BTreeMap<String, u64>,
    pub array_read_borrow_hits: u64,
    pub direct_arg_frame_hits: u64,
    pub direct_method_frame_hits: u64,
    pub direct_closure_frame_hits: u64,
    pub direct_constructor_frame_hits: u64,
    pub argument_vector_allocations_avoided: u64,
    pub prepared_arg_vector_allocations_avoided: u64,
    pub direct_call_source_reads: u64,
    pub direct_call_moves: u64,
    pub direct_call_clones: u64,
    pub direct_call_owned_value_buffers: u64,
    pub cranelift_prepared_arg_materializations: u64,
    pub cranelift_direct_slot_marshals: u64,
    pub direct_frame_fallback_by_reason: BTreeMap<String, u64>,
    pub symbolized_call_name_hits: u64,
    pub symbolized_method_name_hits: u64,
    pub symbolized_property_name_hits: u64,
    pub symbolized_array_key_hits: u64,
    pub symbolized_name_fallbacks_by_reason: BTreeMap<String, u64>,
    pub array_dim_fetches: u64,
    pub packed_dim_fast_path_hits: u64,
    pub packed_dim_fast_path_misses: u64,
    pub array_packed_append_fast_path_hits: u64,
    pub array_packed_read_fast_path_hits: u64,
    pub array_sequential_foreach_fast_path_hits: u64,
    pub array_fast_path_hits_by_family: BTreeMap<String, u64>,
    pub array_fast_path_fallback_by_reason: BTreeMap<String, u64>,
    pub array_shape_observed_by_kind: BTreeMap<String, u64>,
    pub record_shape_hits: u64,
    pub record_shape_misses: u64,
    pub small_map_hits: u64,
    pub small_map_misses: u64,
    pub key_coercion_fallbacks: u64,
    pub order_semantics_fallbacks: u64,
    pub packed_append_fast_hits: u64,
    pub packed_foreach_fast_hits: u64,
    pub cow_or_reference_fallbacks: u64,
    pub array_count_fast_path_hits: u64,
    pub array_packed_to_mixed_transitions: u64,
    pub numeric_string_classify_calls: u64,
    pub numeric_string_cache_hits: u64,
    pub numeric_string_cache_misses: u64,
    pub numeric_string_specialization_hits: u64,
    pub numeric_string_warning_sensitive_fallbacks: u64,
    pub numeric_string_overflow_precision_fallbacks: u64,
    pub array_operation_profiles_by_family: BTreeMap<String, OperationProfile>,
    pub typecheck_fast_path_hits: u64,
    pub typecheck_fast_path_misses: u64,
    pub output_bytes: u64,
    pub output_buffer_appends: u64,
    pub output_buffer_batch_writes: u64,
    pub output_batched_appends: u64,
    pub output_batch_bytes: u64,
    pub output_buffer_flushes: u64,
    pub output_fast_appends: u64,
    pub output_slow_appends_by_reason: BTreeMap<String, u64>,
    pub output_operation_profiles_by_family: BTreeMap<String, OperationProfile>,
    pub internal_function_dispatches: u64,
    pub internal_function_dispatch_cache_hits: u64,
    pub internal_function_dispatch_cache_misses: u64,
    pub internal_count_array_direct_fast_path_hits: u64,
    pub function_call_ic_hits: u64,
    pub function_call_ic_misses: u64,
    pub builtin_call_ic_hits: u64,
    pub builtin_call_ic_misses: u64,
    pub builtin_fast_stub_hits: BTreeMap<String, u64>,
    pub builtin_fast_stub_misses: BTreeMap<String, u64>,
    pub builtin_fast_stub_fallback_by_reason: BTreeMap<String, u64>,
    pub builtin_intrinsic_candidates: u64,
    pub intrinsic_hits: BTreeMap<String, u64>,
    pub intrinsic_misses: BTreeMap<String, u64>,
    pub intrinsic_fallback_by_reason: BTreeMap<String, u64>,
    pub json_encode_fast_path_hits: u64,
    pub json_encode_fast_path_bytes: u64,
    pub json_encode_generic_fallback_by_reason: BTreeMap<String, u64>,
    pub array_slice_packed_fast_hits: u64,
    pub count_array_shape_fast_hits: u64,
    pub map_update_slot_fast_hits: u64,
    pub property_dim_assign_in_place_hits: u64,
    pub property_dim_assign_generic_by_reason: BTreeMap<String, u64>,
    pub property_dim_probe_borrowed_hits: u64,
    pub cufa_owned_argument_moves: u64,
    pub cufa_shared_argument_clones: u64,
    pub array_builtin_fast_fallback_by_reason: BTreeMap<String, u64>,
    pub slow_path_calls_by_reason: BTreeMap<String, u64>,
    pub value_clone_by_reason: BTreeMap<String, u64>,
    pub by_ref_arg_location_binding_attempts: u64,
    pub by_ref_arg_location_bindings: u64,
    pub by_ref_arg_value_materializations: u64,
    pub by_ref_arg_register_pins: u64,
    pub by_ref_arg_cow_separations: u64,
    pub by_ref_arg_cow_separations_avoided: u64,
    pub by_ref_arg_fallback_by_reason: BTreeMap<String, u64>,
    pub call_ic_megamorphic_fallbacks: u64,
    pub local_slot_fast_path_hits: u64,
    pub local_slot_fast_path_misses: u64,
    pub property_fetches: u64,
    pub property_accesses: u64,
    pub type_checks: u64,
    pub includes: u64,
    pub autoloads: u64,
    pub include_resolution_hits: u64,
    pub include_resolution_misses: u64,
    pub include_compile_hits: u64,
    pub include_compile_misses: u64,
    pub include_once_skips: u64,
    pub include_fallback_by_reason: BTreeMap<String, u64>,
    pub include_stale_invalidation_by_reason: BTreeMap<String, u64>,
    pub include_graph_hits: u64,
    pub directory_version_hits: u64,
    pub directory_version_misses: u64,
    pub composer_fingerprint_present: u64,
    pub composer_fingerprint_missing: u64,
    pub composer_fingerprint_stale: u64,
    pub negative_include_cache_hits: u64,
    pub negative_include_cache_installs: u64,
    pub negative_include_cache_invalidations: u64,
    pub negative_include_cache_blocked_by_reason: BTreeMap<String, u64>,
    pub include_graph_misses: u64,
    pub autoload_graph_hits: u64,
    pub autoload_graph_misses: u64,
    pub negative_lookup_hits: u64,
    pub invalidations_by_reason: BTreeMap<String, u64>,
    pub fallback_by_path_semantics: BTreeMap<String, u64>,
    pub string_concats: u64,
    pub string_concat_fast_path_hits: u64,
    pub string_concat_fast_path_misses: u64,
    pub concat_prealloc_hits: u64,
    pub concat_fallback_by_reason: BTreeMap<String, u64>,
    pub guard_failures: u64,
    pub cache_hits: u64,
    pub cache_misses: u64,
    pub literal_intern_hits: u64,
    pub literal_intern_misses: u64,
    pub native_candidates: u64,
    pub native_compiled_regions: u64,
    pub native_executions: u64,
    pub native_compile_budget_rejections: u64,
    pub native_eligibility_rejections_by_reason: BTreeMap<String, u64>,
    pub native_side_exits_by_reason: BTreeMap<String, u64>,
    pub native_blacklist_suppression_by_unstable_region: BTreeMap<String, u64>,
    pub jit_compile_attempts: u64,
    pub jit_compiled: u64,
    pub jit_executed: u64,
    pub jit_bailouts: u64,
    pub jit_code_bytes: u64,
    pub jit_compile_time_nanos: u64,
    pub jit_side_exits: u64,
    pub jit_side_exit_reasons: BTreeMap<String, u64>,
    pub jit_guard_failures: u64,
    pub jit_blacklisted_regions: u64,
    pub jit_blacklist_reasons: BTreeMap<String, u64>,
    pub jit_tiering_cold_functions: u64,
    pub jit_tiering_hot_functions: u64,
    pub jit_tiering_eager_functions: u64,
    pub jit_tiering_blacklist_rejections: u64,
    pub jit_tiering_budget_rejections: u64,
    pub jit_helper_calls: u64,
    pub jit_fast_path_hits: u64,
    pub compiled_to_compiled_calls: u64,
    pub packed_fetch_fast_hits: u64,
    pub record_lookup_fast_hits: u64,
    pub record_lookup_key_miss_exits: u64,
    pub record_lookup_layout_exits: u64,
    pub packed_fetch_bounds_exits: u64,
    pub packed_fetch_layout_exits: u64,
    pub packed_fetch_bounds_fallbacks: u64,
    pub packed_fetch_layout_fallbacks: u64,
    pub packed_foreach_sum_fast_hits: u64,
    pub packed_foreach_sum_layout_exits: u64,
    pub packed_foreach_sum_overflow_exits: u64,
    pub known_call_fast_hits: u64,
    pub known_call_guard_exits: u64,
    pub known_call_slow_calls: u64,
    pub direct_call_hits: u64,
    pub direct_call_fallbacks: u64,
    pub property_load_fast_hits: u64,
    pub property_load_guard_exits: u64,
    pub property_load_layout_exits: u64,
    pub property_load_uninitialized_exits: u64,
    pub property_load_slow_calls: u64,
    pub jit_overflow_exits: u64,
    pub jit_slow_path_calls: u64,
    pub jit_compile_cache_hits: u64,
    pub jit_compile_cache_misses: u64,
    pub jit_compile_cache_invalidations: u64,
    pub jit_process_cache_hits: u64,
    pub jit_process_cache_misses: u64,
    pub jit_compile_waits: u64,
    pub jit_duplicate_compiles_avoided: u64,
    pub jit_code_bytes_live: u64,
    pub jit_code_bytes_retired: u64,
    pub jit_code_generations: u64,
    pub jit_evictions: u64,
    pub jit_compile_descriptors: Vec<JitCompileDescriptor>,
    pub inline_cache_observations: u64,
    pub inline_cache_slots: u64,
    pub inline_cache_function_slots: u64,
    pub inline_cache_method_slots: u64,
    pub inline_cache_property_slots: u64,
    pub inline_cache_property_assign_slots: u64,
    pub inline_cache_dim_slots: u64,
    pub inline_cache_class_constant_static_property_slots: u64,
    pub inline_cache_class_relation_slots: u64,
    pub inline_cache_include_path_slots: u64,
    pub inline_cache_autoload_class_lookup_slots: u64,
    pub inline_cache_hits: u64,
    pub inline_cache_misses: u64,
    pub inline_cache_invalidations: u64,
    pub inline_cache_guard_failures: u64,
    pub inline_cache_resolver_requests: u64,
    pub inline_cache_monomorphic: u64,
    pub inline_cache_polymorphic: u64,
    pub inline_cache_megamorphic: u64,
    pub inline_cache_disabled: u64,
    pub method_ic_hits: u64,
    pub method_ic_misses: u64,
    pub method_ic_polymorphic_hits: u64,
    pub method_ic_guard_failures: u64,
    pub method_direct_dispatch_hits: u64,
    pub method_direct_dispatch_fallbacks: u64,
    pub method_tiny_inline_candidates: u64,
    pub method_inline_candidates: u64,
    pub method_inline_hits: u64,
    pub method_inline_fallback_by_reason: BTreeMap<String, u64>,
    pub constructor_inline_hits: u64,
    pub dto_array_inline_hits: u64,
    pub sort_callback_resolution_cache_hits: u64,
    pub sort_callback_direct_call_hits: u64,
    pub sort_callback_generic_fallback_by_reason: BTreeMap<String, u64>,
    pub method_tiny_inline_rejected_by_reason: BTreeMap<String, u64>,
    pub property_ic_hits: u64,
    pub property_ic_misses: u64,
    pub property_ic_guard_failures: u64,
    pub property_ic_fallback_reasons: BTreeMap<String, u64>,
    pub property_assign_ic_hits: u64,
    pub property_assign_ic_misses: u64,
    pub property_assign_ic_guard_failures: u64,
    pub property_assign_ic_shape_exits: u64,
    pub property_assign_ic_visibility_exits: u64,
    pub property_assign_ic_type_exits: u64,
    pub property_assign_ic_readonly_exits: u64,
    pub property_assign_ic_hook_magic_exits: u64,
    pub property_assign_ic_reference_exits: u64,
    pub property_assign_ic_dynamic_exits: u64,
    pub property_assign_ic_fallback_reasons: BTreeMap<String, u64>,
    pub object_operation_profiles_by_family: BTreeMap<String, OperationProfile>,
    pub class_static_ic_hits: u64,
    pub class_static_ic_misses: u64,
    pub class_static_ic_guard_failures: u64,
    pub class_relation_cache_hits: u64,
    pub class_relation_cache_misses: u64,
    pub class_relation_cache_invalidations: u64,
    pub instanceof_cache_hits: u64,
    pub instanceof_cache_misses: u64,
    pub method_override_cache_hits: u64,
    pub method_override_cache_misses: u64,
    pub include_path_ic_hits: u64,
    pub include_path_ic_misses: u64,
    pub include_path_ic_invalidations: u64,
    pub include_path_ic_guard_failures: u64,
    pub autoload_class_lookup_ic_hits: u64,
    pub autoload_class_lookup_ic_misses: u64,
    pub autoload_class_lookup_ic_invalidations: u64,
    pub autoload_class_lookup_ic_guard_failures: u64,
    pub property_fetch_profiles: BTreeMap<String, PropertyFetchProfile>,
    pub method_call_profiles: BTreeMap<String, MethodCallProfile>,
}

impl VmCounters {
    #[must_use]
    pub fn to_json(&self) -> String {
        format!(
            concat!(
                "{{\n",
                "  \"schema_version\": 3,\n",
                "  \"native_compiled_regions\": {},\n",
                "  \"native_executions\": {},\n",
                "  \"native_compile_budget_rejections\": {},\n",
                "  \"jit_code_bytes\": {},\n",
                "  \"jit_compile_time_nanos\": {},\n",
                "  \"jit_side_exits\": {},\n",
                "  \"jit_helper_calls\": {},\n",
                "  \"jit_code_generations\": {}\n",
                "}}\n"
            ),
            self.native_compiled_regions,
            self.native_executions,
            self.native_compile_budget_rejections,
            self.jit_code_bytes,
            self.jit_compile_time_nanos,
            self.jit_side_exits,
            self.jit_helper_calls,
            self.jit_code_generations,
        )
    }
}
